### ISSUE TITLE
docker 兼容性问题

### ISSUE THREAD

**Issue by LEON121** [terwer/siyuan-plugin-publisher#1009]
Docker版本2.12.3 思源笔记现在是不兼容吗？
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/37445848/cc030a84-f5ce-45cf-80fb-4af802e141a4)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/37445848/20f36ed2-44ff-4a33-8a1f-15d81dfc5ea8)

**Comment by terwer** [comment]
docker 版本持续适配中，适配完了，会放出来开关。暂时可先使用 pc 版本，等适配完了会放出来。

**Comment by terwer** [comment]
逐个平台开启兼容测试，进度如下：
https://github.com/terwer/siyuan-plugin-publisher/tree/dev?tab=readme-ov-file#platform-list
