### ISSUE TITLE
发布到自建typecho不渲染公式，用markdown形式发布格式没有渲染。

### ISSUE THREAD

**Issue by dengxuezhao** [terwer/siyuan-plugin-publisher#1020]
我现在在做发布测试
用html格式发布效果：https://blog.xuezhao.space/index.php/archives/3/
用markdown格式发布效果：https://blog.xuezhao.space/index.php/archives/6/
两种情况公式都不渲染，用markdown发布的结果是源码。
这是我的配置：
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/43956952/75f1c2bb-ac61-499a-8269-a4a0c5528c87)
还有一个错误：
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/43956952/9a2f2650-a48b-4371-9b3c-3b9ecf424412)

**Comment by terwer** [comment]
1、typecho 公式问题，请参照此文章 https://blog.terwer.space/static/20240227143900-be07wt1 或者 https://blog.terwergreen.com/typecho-platform-configuration-guide-1htgmj.html 解决

2、发布格式暂时只能支持 html 模式。

3、错误可以先强制删除再试试，常规发布点击强制删除或者点击后面的强制接触关联。
