### ISSUE TITLE
在csdn上发布到最后失败，提示没有文章标签

### ISSUE THREAD

**Issue by work4blue** [terwer/siyuan-plugin-publisher#1024]
如何在文章设立标签？

**Comment by terwer** [comment]
这个我已经说明了，csdn 必须添加标签，这是 CSDN 的限制，请添加标签之后在发布，直接在思源笔记加标签即可，在思源笔记标题的上方可以新增标签。或者使用单个发布切换详细模式也可以



---- 回复的原邮件 ----
| 发件人 | Andrew ***@***.***> |
| 日期 | 2024年02月07日 22:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-publisher] 在csdn上发布到最后失败，提示没有文章标签 (Issue #1024) |

如何在文章设立标签？

**Comment by work4blue** [comment]
发布成功，原来是直接在文章内部加标签发布失败，必须是顶部设置标签，谢谢
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/1583762/54e1c8fb-37fa-47cb-8d7b-1ffc10b77734)
