### ISSUE TITLE
支持 Telegraph 发布和更新

### ISSUE THREAD

**Issue by isPoto** [terwer/siyuan-plugin-publisher#1053]
希望能有插件支持发布至 Telegraph ，Telegram 旗下的文章发布平台

支持发布以及更新笔记后同步更新 Telegraph 端

**Comment by terwer** [comment]
参考这篇文章的介绍：https://telegra.ph/Telegraph--%E7%AE%80%E6%B4%81%E7%9A%84%E6%96%87%E7%AB%A0%E5%8F%91%E5%B8%83%E5%B9%B3%E5%8F%B0-08-26

# 官网

[telegra.ph](https://telegra.ph/)

**Comment by terwer** [comment]
注意：此功能需要科学上网，请自行解决科学上网的问题。

**Comment by isPoto** [comment]
> 注意：此功能需要科学上网，请自行解决科学上网的问题。

行
