### ISSUE TITLE
Halo发布解析MD出现问题、希望增加缩略图的设置项、AI生成摘要老是报错

### ISSUE THREAD

**Issue by sumruler** [terwer/siyuan-plugin-publisher#1093]
1. 通过Halo发布的时候，文章页面的Markdown语法似乎没有被解析，需要到Halo后台重新发布一遍才可以
![Clip_2024-03-10_23-28-18](https://github.com/terwer/siyuan-plugin-publisher/assets/56953545/12e76e4a-bed0-4971-9722-0e4702bcd4a6)
2. 文章利用AI自动提取摘要的时候，老是提示文章内容太少，无法提取
3. 建议在发布的时候可以设置文章的缩略图，增加一个填写缩略图的输入框。

最后感谢开发者的制作，非常方便好用！

**Comment by terwer** [comment]
1、halo 仅支持设置为 HTML。
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/fc3ba757-358c-4875-a6dc-9b8ac24a907a)

2、AI 没有内容可能是文本太长，目前没有自动截取，文章超过 token 限制会失败。后续考虑自定优化请求 token 长度，自动截取。

3、缩略图可以考虑，但是需要平台支持，每个平台都不一样，需要考虑如何统一的问题。后续会先调研。

**Comment by sumruler** [comment]
您好，我尝试改成HTML，发布的时候仍然有问题，平台是Halo

**Comment by sumruler** [comment]
您好，我尝试改成HTML，发布的时候仍然有问题，平台是Halo，版本是2.13，会不会是这个发布工具针对1版本，所以在2版本出现此问题呢？

**Comment by terwer** [comment]
针对 2 开发的，我这里是没问题的，你那具体是啥问题，要说清楚一点



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月11日 19:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [terwer/siyuan-plugin-publisher] Halo发布解析MD出现问题、希望增加缩略图的设置项、AI生成摘要老是报错 (Issue #1093) |

您好，我尝试改成HTML，发布的时候仍然有问题，平台是Halo，版本是2.13，会不会是这个发布工具针对1版本，所以在2版本出现此问题呢？
