### ISSUE TITLE
添加知乎平台时授权提示“请求参数异常”

### ISSUE THREAD

**Issue by owlright** [terwer/siyuan-plugin-publisher#1126]
![屏幕截图 2024-03-23 202508](https://github.com/terwer/siyuan-plugin-publisher/assets/71282734/23338345-169c-428e-8179-62f881078df3)

**Comment by terwer** [comment]
文档有说明，知乎必须扫码登录，没别的办法了。 https://blog.terwer.space/s/20230810132040-nn4q7vs
请看这里 FAQ9 知乎说明


| |
youweics
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月23日 20:31 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-publisher] 添加知乎平台时授权提示“请求参数异常” (Issue #1126) |

2024-03-23.202508.png (view on web)
