### ISSUE TITLE
新版本提示：未指定图片服务，不处理图片

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#1171]
之前配置了Github图床，并且重新配置依然提示没有指定
![Clip_2024-04-16_15-42-09](https://github.com/terwer/siyuan-plugin-publisher/assets/60436214/4654229e-bfdf-4cec-87cb-50e22535c11b)

**Comment by terwer** [comment]
请在发布工具的配置页面图床服务手动选择，当前平台。新版本可以在发布工具的平台配置里面自由开启关闭图床。


| |
youweics
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月16日 15:42 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-publisher] 更新版本后提示：未指定图片服务，不处理图片 (Issue #1171) |

之前配置了Github图床
Clip_2024-04-16_15-42-09.png (view on web)

**Comment by Achuan-2** [comment]
我打开平台设置，保存之后，才上传成功

**Comment by terwer** [comment]
> 我打开平台设置，保存之后，才上传成功

是的，需要这个操作。这个文档没来得及更新。我置顶一下，方便其他人参考。

**Comment by Achuan-2** [comment]
自由关闭图床这个功能有应用场景吗？感觉没有太大必要

**Comment by terwer** [comment]
对于 WordPress、Typecho、博客园这种既可以用图床插件，也可以直接传到后台的有用。对于 GitHub 这种其实没有必要。但是这个是对所有平台统一控制的，所以就加上了。

**Comment by 834116404** [comment]
> 请在发布工具的配置页面图床服务手动选择，当前平台。新版本可以在发布工具的平台配置里面自由开启关闭图床。 | | youweics | | ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年04月16日 15:42 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> | | 主题 | [terwer/siyuan-plugin-publisher] 更新版本后提示：未指定图片服务，不处理图片 (Issue #1171) | 之前配置了Github图床 Clip_2024-04-16_15-42-09.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

没找到设置图床的地方

**Comment by terwer** [comment]
各个平台的设置里面都有

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/8ddd38ac-732e-4052-bf8b-d5a68921321c)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/cbaa1f91-6206-47e8-be68-34fb959d876d)
