### ISSUE TITLE
notion连接成功后显示检测到旧配置，正在迁移配置，一直不能发布成功？

### ISSUE THREAD

**Issue by xuguangjian** [terwer/siyuan-plugin-publisher#1192]
检测到旧配置，正在迁移配置，已经20分钟了，这个需要我重装插件嘛？
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/66892415/cd76c47f-2cd5-49ef-95b0-5cf1fe47d92f)

**Comment by terwer** [comment]
这个是图床插件的提示，在迁移旧的图床配置，重启软件试试看。


| |
youweics
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月23日 16:15 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-publisher] notion连接成功后显示检测到旧配置，正在迁移配置，一直不能发布成功？ (Issue #1192) |

检测到旧配置，正在迁移配置，已经20分钟了，这个需要我重装插件嘛？
image.png (view on web)

**Comment by xuguangjian** [comment]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/66892415/408a3a2c-1204-4ec5-a50d-340e7deb08e0)
 没啥用，语雀就可以正常发，就是notion不太行

**Comment by terwer** [comment]
好的，我排查一下。

**Comment by xuguangjian** [comment]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/66892415/cc23baae-b47f-4aa6-be7d-efc3e5e07a78)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/66892415/73b1ae30-4419-443b-aa2b-80b7bda83f3b)

说我未指定上传图片服务，但是我已经设置好了图床服务啊？

**Comment by terwer** [comment]
发布工具设置里面要勾上，图床和发布工具不是强制绑定的。

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/0e7a2487-7296-4ce7-bd60-1488258bba3e)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/01e5865d-434f-4fb3-8cb5-c6ace4178562)

**Comment by xuguangjian** [comment]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/66892415/54b4ce37-1061-4679-ac3a-707d027ca639)
这个我知道的，大不了就不发布到notion了，直接复制问题也不大

**Comment by buyaofangqi** [comment]
勾选了PicGO插件并保存验证了，还是一直显示检测到旧配置，正在迁移配置

**Comment by xuguangjian** [comment]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/66892415/68e3af4b-5e0e-40b2-b530-643a6840233a)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/66892415/6b62e4da-4cc8-450b-88a1-acf80a2d3b1c)
是的， 都勾选了；这个确定过的
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/66892415/e3492bac-f6aa-46a0-b3d3-0646da803a9f)
一直在这里转圈圈

**Comment by xuguangjian** [comment]
其他俩都发布成功了，就是图片没有发布的了，图床也能上传成功，发布到语雀就没有图片，不知道那里出了问题
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/66892415/845141fa-51fb-4fc7-91ec-24666fde87fd)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/66892415/0be97a10-a7d5-45a2-91d3-bf06f7a38441)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/66892415/57ccf879-6632-4367-9fe0-dfa9a33dc56d)

**Comment by terwer** [comment]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/7d0d8636-c6f4-4f69-aff3-8ea1ac6f4772)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/aebf7d69-405c-4a4f-8c12-b8c7284f08d3)


问题无法复现。请提供详细的环境、必现步骤。

**Comment by xuguangjian** [comment]
我把两个插件删除了，把缓存全部删掉，两天后我重装一下重新测试，到时候录一个视频。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月24日 09:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [terwer/siyuan-plugin-publisher] notion连接成功后显示检测到旧配置，正在迁移配置，一直不能发布成功？ (Issue #1192) |

image.png (view on web)
问题无法复现。请提供详细的环境】必现步骤。
