### ISSUE TITLE
未指定上传图片服务器

### ISSUE THREAD

**Issue by 834116404** [terwer/siyuan-plugin-publisher#1196]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/36099756/18adc0b5-0a76-46bb-8dca-2fd1d078e629)

找不到设置图床的地方

**Comment by terwer** [comment]
各个平台的设置里面都有

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/8ddd38ac-732e-4052-bf8b-d5a68921321c)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/cbaa1f91-6206-47e8-be68-34fb959d876d)
