### ISSUE TITLE
操作失败=>TypeError: ((intermediate value)(intermediate value)(intermediate value) ?? []) is not iterable v3.0.10

### ISSUE THREAD

**Issue by 834116404** [terwer/siyuan-plugin-publisher#1197]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/36099756/609b223a-68fa-4fce-82c2-4edc6d6c104c)

操作失败=>TypeError: ((intermediate value)(intermediate value)(intermediate value) ?? []) is not iterable v3.0.10

**Comment by terwer** [comment]
需要详细的环境、复现步骤。我这里没能复现。

**Comment by 834116404** [comment]
> 需要详细的环境、复现步骤。我这里没能复现。

下次我试试, 这个是偶现的,

**Comment by terwer** [comment]
等有了稳定复现步骤再开启，

**Comment by 834116404** [comment]
> 等有了稳定复现步骤再开启，

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/36099756/82ec331e-f19e-4e6a-b9de-f229f988f182)


常规发布就出现了

**Comment by 834116404** [comment]
> > 等有了稳定复现步骤再开启，
> 
> ![image](https://private-user-images.githubusercontent.com/36099756/326226090-82ec331e-f19e-4e6a-b9de-f229f988f182.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNzM3OTEsIm5iZiI6MTcxNDI3MzQ5MSwicGF0aCI6Ii8zNjA5OTc1Ni8zMjYyMjYwOTAtODJlYzMzMWUtZjE5ZS00ZTZhLWI5ZGUtZjIyOWY5ODhmMTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAzMDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZWJlYzRhZDZmNWI5YmQwMDI0NDU3MTMzYTFkY2RiZDg4ZDExZDM3MGNlM2M1Y2E2OGIyNGI2YWZmMDdhYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HncapZjMdFrCoDDy3SPYRO6ZEZn1w-FeE8xXo0pOwsE)
> 
> 常规发布就出现了

感觉是偶发的..

**Comment by terwer** [comment]
我这边尝试下检查代码看看能不能复现。

**Comment by terwer** [comment]
可升级到 `v1.30.2`，看看是否已修复。
