### ISSUE TITLE
可以自定义源码模式吗

### ISSUE THREAD

**Issue by huameiwei-vc** [terwer/siyuan-plugin-publisher#1199]
---
title: 博客
date: '2024-04-23 08:14:10'
updated: '2024-04-24 16:13:39'
permalink: /post/blog-z22atcp.html
comments: true
toc: true
---
permalink这个可以改吗？或者删除。
还是必须每次都手动改？

**Comment by terwer** [comment]
可以删除啊，配置里面禁用就永久禁用行了。这里的配置的禁用是永久的。

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/5db95754-e2af-4c96-8a3e-765fbbf99ea1)

修改的话，也可能也可以每次临时修改，改好了记得保存。这个修改是临时的。

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/493d2d8e-442d-4679-9007-af4001a77d87)

**Comment by huameiwei-vc** [comment]
> 可以删除啊，配置里面禁用就永久禁用行了。这里的配置的禁用是永久的。
> 
> ![image](https://private-user-images.githubusercontent.com/3259282/325139051-5db95754-e2af-4c96-8a3e-765fbbf99ea1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMDUxMjQsIm5iZiI6MTcxNDAwNDgyNCwicGF0aCI6Ii8zMjU5MjgyLzMyNTEzOTA1MS01ZGI5NTc1NC1lMmFmLTRjOTYtOGEzZS03NjVmYmJmOTllYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjVUMDAyNzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmI0Zjg5M2VjZDYxMjY4ZDhjM2UzMDhmYjg3MTU3NDM4NjAyNjVmMzcyOGFmNzYyZDM0NWM1YTBjYTUzMTQ5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FWO3N0uctMpiMGT3ZPVU1Ozx_DsY46y40rXqArAAHlk)
> 
> 修改的话，也可能也可以每次临时修改，改好了记得保存。这个修改是临时的。
> 
> ![image](https://private-user-images.githubusercontent.com/3259282/325139494-493d2d8e-442d-4679-9007-af4001a77d87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMDUxMjQsIm5iZiI6MTcxNDAwNDgyNCwicGF0aCI6Ii8zMjU5MjgyLzMyNTEzOTQ5NC00OTNkMmQ4ZS00NDJkLTQ2NzktOTAwNy1hZjQwMDFhNzdkODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjVUMDAyNzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjIyMWRkMTlkM2RjN2Y2OTg5MWE5NDlkZmJiYjBkYmNiZTEyOWY0YTY4MzVhNGViZTcwMzk2ZTMzMzI2OWExOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XSXn0T4d5HLUf05X2tmN3h-5YIN28icS-Q6UjilX3Go)

谢谢~很抱歉，没看到。。。
