### ISSUE TITLE
目前文章里有块引就发布不了

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#1202]
能否添加一个设置，块引文本变为普通文本选项呢？
毕竟也不是所有块引笔记都需要发到网上去的。

**Comment by terwer** [comment]
这个是在思源笔记里面设置的，你可以在导出选项里面设置



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月27日 11:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-publisher] 目前文章里有块引就发布不了 (Issue #1202) |

能否添加一个设置，块引文本变为普通文本选项呢？
毕竟也不是所有块引笔记都需要发到网上去的。

**Comment by terwer** [comment]
或者加个选项也行，但是要看是什么全局，还是单个平台



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月27日 11:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-publisher] 目前文章里有块引就发布不了 (Issue #1202) |

能否添加一个设置，块引文本变为普通文本选项呢？
毕竟也不是所有块引笔记都需要发到网上去的。

**Comment by Achuan-2** [comment]
> 这个是在思源笔记里面设置的，你可以在导出选项里面设置

好的，确实思源笔记设置为导出为锚文本就可以导出了
那就没有太大必要加选项了。

**Comment by Achuan-2** [comment]
亲测，最新版本块引导出选项设置为导出锚文本，依然无法导出有块引的文章

**Comment by Achuan-2** [comment]
这个问题还是没有解决，块引导出选项设置为导出锚文本，依然无法导出有块引的文章

**Comment by terwer** [comment]
`v1.30.1` 已优化

新增设置
通用设置->偏好设置->忽略块引用

![image](https://github.com/user-attachments/assets/3fae64d4-20af-47b9-989a-3056bea543d5)

## 默认为 false，就是不忽略，发现块引用的未发布就会阻止发布并报错。效果

![image](https://github.com/user-attachments/assets/abe59a4b-beee-4a0f-a5ad-03933031aa6e)

![image](https://github.com/user-attachments/assets/d0fb48b6-ec14-4493-93a8-0b0ff9e2c0d0)


## 如果勾选之后，会忽略检测，块链接设置为 block://xxxxxxx

![image](https://github.com/user-attachments/assets/31902ce0-f3fe-43cc-bbcd-5b38d48ed7a6)

![image](https://github.com/user-attachments/assets/a149ebdc-3056-4c52-baaa-283fb129e30f)

![image](https://github.com/user-attachments/assets/28d5c849-d6ad-4806-99a9-be39207f7bf5)

**Comment by terwer** [comment]
fixed in `v1.30.1`

**Comment by Achuan-2** [comment]
感谢大佬
不过忽略块引用的话，是不是应该改为纯文本呢

**Comment by terwer** [comment]
> 感谢大佬 不过忽略块引用的话，是不是应该改为纯文本呢

感谢建议，下版本考虑改动。

**Comment by terwer** [comment]
show plain text when cfg is enabled is fixed in `v1.30.2`

**Comment by Achuan-2** [comment]
感谢大佬，发现新版本已经开始支持哔哩哔哩了，太强了！
