### ISSUE TITLE
Hexo 平台设置别名不生效

### ISSUE THREAD

**Issue by terwer** [terwer/siyuan-plugin-publisher#1231]
[slug].md修改之后保存会重置

**Comment by Achuan-2** [comment]
此外，设置别名还有问题
如果别名有多个
![Clip_2024-08-11_19-49-05](https://github.com/user-attachments/assets/7c140309-3cbe-4cef-87ae-79d528d3bc1f)
文章别名就成了这个
![Clip_2024-08-11_19-49-45](https://github.com/user-attachments/assets/89dcf269-e7aa-410f-990a-8afab54a7d3a)
实际md名称为Wilcoxon，貌似会被空格阶段，还没有md后缀

**Comment by Achuan-2** [comment]
> 此外，设置别名还有问题 如果别名有多个 ![Clip_2024-08-11_19-49-05](https://private-user-images.githubusercontent.com/60436214/356871231-7c140309-3cbe-4cef-87ae-79d528d3bc1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTA2NTIsIm5iZiI6MTcyODA5MDM1MiwicGF0aCI6Ii82MDQzNjIxNC8zNTY4NzEyMzEtN2MxNDAzMDktM2NiZS00Y2VmLTg3YWUtNzlkNTI4ZDNiYzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDAxMDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0OGFhYzg4MzYxOTZjNmNkNDFlNWI4NDgyMmU0NThiMTRmZGM1YmMyZDRkZTYyZmZjOTJhY2U2NTU0NTgyNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yofI5rnM9OXv6SVwd0zYqHrleR024gi-c67XlaQxanM) 文章别名就成了这个 ![Clip_2024-08-11_19-49-45](https://private-user-images.githubusercontent.com/60436214/356871249-89dcf269-e7aa-410f-990a-8afab54a7d3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTA2NTIsIm5iZiI6MTcyODA5MDM1MiwicGF0aCI6Ii82MDQzNjIxNC8zNTY4NzEyNDktODlkY2YyNjktZTdhYS00MTBmLTk5MGEtOGFmYWI1NGE3ZDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDAxMDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZTcwYjA4YTQxMDljZjcwZjQ0NjQ3ZDUxNDNkZjQ3YWJjZTBlMzY0NTBkOWYxYmZlYmQ4YTRiYjlkMmViMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._BuYsqTDbQciY07F048cEKMufCfG0pGNk5UAbWE-Kb8) 实际md名称为Wilcoxon，貌似会被空格阶段，还没有md后缀

这个问题还没有解决，导致我设置多个别名的笔记都无法发布

**Comment by Achuan-2** [comment]
[slug].md
[slug]代表什么
能修改成什么变量

---

哦哦，slug就有别名的意思

**Comment by terwer** [comment]
slug保存在 custom-slug ,这个在 /data/storage/syp/sy-p-plus-cfg.json 里面（为什么存在这里。这是历史设计。暂时不适合调整了。），最终错误是因为github 名称空格不允许空格。
为什么我推荐设置 [slug].md 就是因为 github 通过 api 没有办法绕过别名不能为空这个限制。gitlab 没这个问题。我自动生成的不会有空格。

```
  // 别名
      const slug = ObjectUtil.getProperty(postMeta, SiyuanAttr.Custom_slug, post.wp_slug)
      if (!StrUtil.isEmptyString(slug)) {
        post.wp_slug = slug
        logger.info("Using existing siyuan note slug")
      } else {
        // 如果wp_slug为空，则生成一个新的slug
        const slug = await AliasTranslator.getPageSlug(post.title, true)
        post.wp_slug = `${slug}`
        logger.info("Generated new slug")
      }
````


这个逻辑是这样：
1、优先获取 custom-slug，有的话直接返回
2、没有，会尝试使用标题名称新生成一个。

![image](https://github.com/user-attachments/assets/a5eb56f2-4972-4bac-a88d-2adaec74768d)

他使用会优先调用翻译 api 生成。失败使用拼音。

https://github.com/terwer/siyuan-plugin-publisher/blob/main/src/composables/usePublish.ts#L371

https://github.com/terwer/zhi/blob/main/libs/zhi-common/src/lib/slugUtil.ts#L120


我看了下问题可能出现在，      
const slug = ObjectUtil.getProperty(postMeta, SiyuanAttr.Custom_slug, post.wp_slug)

post.wp_slug 的读取逻辑，先读取 Custom_slug找不到，获取系统别名。这样的话我考虑去掉这个

![image](https://github.com/user-attachments/assets/068545d5-80e9-4120-9e6d-e768bce0311f)

https://github.com/terwer/zhi/blob/main/libs/zhi-siyuan-api/src/lib/adaptor/siYuanApiAdaptor.ts#L234

下版本修复

**Comment by terwer** [comment]
fixed in `v1.29.0`

**Comment by Achuan-2** [comment]
ok，谢谢大佬的耐心回复
辛苦啦
