### ISSUE TITLE
发布csdn的时候，代码块儿语言不显示

### ISSUE THREAD

**Issue by 834116404** [terwer/siyuan-plugin-publisher#1245]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/36099756/038415c5-f992-4e78-878e-be5f5eb2f1e6)

思源笔记是java代码块儿

发布到csdn上不显示java代码块儿

发布完了之后 
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/36099756/e0eab7b1-8b58-49b6-abe8-2ba77aa16365)

代码块儿是黑白的.

然后我点了编辑之后发现文章里面有 ```java
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/36099756/f25e0e16-1f07-41ee-a818-af666cff642a)

我再保存文章,再点进去文章看, 发现代码块儿才是Java的

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/36099756/42e2bd6c-8869-4912-9f3e-3241c6091183)

**Comment by terwer** [comment]
已修复，需要升级 1.12.6。旧文章更新之后也可修复。
