### ISSUE TITLE
发布的时候提示 文档id不能为空

### ISSUE THREAD

**Issue by 834116404** [terwer/siyuan-plugin-publisher#1284]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/36099756/2e688e3b-cec8-4dbc-bda0-610bc68038c3)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/36099756/a261c5a0-285f-45cb-b5f9-a2f24b477379)

**Comment by terwer** [comment]
https://github.com/terwer/siyuan-plugin-publisher/issues/950

看看这个 issue，是不是安装了其他不兼容插件。

**Comment by terwer** [comment]
需要更加稳定的复现步骤
