### ISSUE TITLE
发布的时候存在bug

### ISSUE THREAD

**Issue by 834116404** [terwer/siyuan-plugin-publisher#1285]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/36099756/7be7195d-d1b1-4842-9c9a-49e13ff4c8a4)

发布的时候提示这个错误信息

**Comment by terwer** [comment]
无法复现，最好提供更多信息
![image](https://github.com/user-attachments/assets/cf19ab54-d08b-4b5a-8b00-b2fd27d974b6)
