### ISSUE TITLE
浅浅说下CSDN 初次发布遇到的问题：直接一键发布缺少文章标题的提示

### ISSUE THREAD

**Issue by 12356kkk** [terwer/siyuan-plugin-publisher#1294]
1、初次使用一键发布csdn时，可能会出现：缺少文章标题的提示
2、此时，可以选择进入常规发布中
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/85390862/65036aa6-aae7-4efb-8447-0753249a1fb8)
（下图此处需要点击‘csdn’样式图标，点击卡片其他空白处无法触发事件）
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/85390862/ea864bfb-f31c-474d-aa84-8467c4e8cf9d)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/85390862/2cb92728-6b4c-4a71-aa59-9a9dff520932)
3、完成配置发布
4、若还有其他问题，可以尝试将发布时间更新为当前时间。或者填写好其他基本项
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/85390862/5b5fba1a-3b4f-4c4c-883d-0a15d82d268d)
希望能帮助到遇到一样问题的人哈哈

**Comment by terwer** [comment]
PS：直接在思源笔记标题上方写好标签，然后再一键发布也是可以的。
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/d62fdab3-154a-4df1-8e01-c387d2f64d8b)
