### ISSUE TITLE
halo发布失败

### ISSUE THREAD

**Issue by 89780012** [terwer/siyuan-plugin-publisher#1296]
容器：docker 
镜像：registry.fit2cloud.com/halo/halo:2.16
发布方式: 常规发布
发布报错：
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/32233271/a3e4c2ac-c831-43ef-873e-e083267a25cd)

**Comment by terwer** [comment]
未能复现，需要更加详细的复现步骤。
