### ISSUE TITLE
hugo无法添加自定义属性

### ISSUE THREAD

**Issue by yangtfu** [terwer/siyuan-plugin-publisher#1297]
添加之后所有metadata都会不见

**Comment by terwer** [comment]
看看是不是语法错误，要符合 yaml 的语法，最好给出出错示例。我这里测试正常。

**Comment by yangtfu** [comment]
> 看看是不是语法错误，要符合 yaml 的语法，最好给出出错示例。我这里测试正常。

```
---
title: 测试文档
slug: test-document-tw4uk
url: /post/test-document-tw4uk.html
date: '2024-07-03 14:18:03+08:00'
lastmod: '2024-07-03 15:19:29+08:00'
toc: true
tags:
  - Windows
categories:
  - 折腾
keywords: Windows
isCJKLanguage: true
author: test
---
```

author是后添加的

**Comment by yangtfu** [comment]
发布后结果：
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/14918820/fb248e4f-d6d6-4d48-962c-dcb6b8c8ee2b)

**Comment by yangtfu** [comment]
> 看看是不是语法错误，要符合 yaml 的语法，最好给出出错示例。我这里测试正常。

又试了下，添加切回详细模式再更新正常，直接在源码模式更新就会出现这个问题

**Comment by terwer** [comment]
> > 看看是不是语法错误，要符合 yaml 的语法，最好给出出错示例。我这里测试正常。
> 
> 又试了下，添加切回详细模式再更新正常，直接在源码模式更新就会出现这个问题

这样的话要么在源码模式禁止使用更新功能。要么源码模式的更新修复一下。算是 bug。

**Comment by terwer** [comment]
这块逻辑更新了下，更新到 `v1.29.2` 试试
