### ISSUE TITLE
vitepress不支持自定义文件规则，只能用[slug].md

### ISSUE THREAD

**Issue by LeonYoah** [terwer/siyuan-plugin-publisher#1301]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/95527066/a2c6436c-ad0f-4879-972e-a57639ddf5b8)
baocunwe保存无效

**Comment by terwer** [comment]
已修复。最新版 `v1.29.2` 支持更多个性化配置

https://github.com/terwer/siyuan-plugin-publisher/issues/1495
