### ISSUE TITLE
Halo 平台发布格式异常

### ISSUE THREAD

**Issue by mdzz2048** [terwer/siyuan-plugin-publisher#1324]
## 系统信息

思源笔记版本：v3.1.1
发布工具插件：v1.21.6
Halo 平台版本：v2.17.1（使用 Docker 运行）

----

发布格式设置为 HTML 格式，实际发布格式为 Markdown 格式

![image](https://github.com/user-attachments/assets/9debea4c-3428-4372-8b7a-868fc4867b79)

![image](https://github.com/user-attachments/assets/333a007a-7aa8-44e0-be49-814ad4ae13fd)

通过开发者工具查看 API 载荷中也是 Markdown 格式

![image](https://github.com/user-attachments/assets/8f0270f0-3ea9-4784-9c98-8f2b9addefd9)

**Comment by yss930819** [comment]
我是选择了 markdown 模式但是发布上去是 html

![image](https://github.com/user-attachments/assets/4ed276b2-2120-4db6-aff2-31089f1d9222)

![image](https://github.com/user-attachments/assets/e649809a-e60d-4810-a3d5-3f8abd475152)
