### ISSUE TITLE
“检测到旧配置”的错误提示

### ISSUE THREAD

**Issue by xiyan818** [terwer/siyuan-plugin-publisher#1336]
![image](https://github.com/user-attachments/assets/759646d8-b5fa-413d-94ba-6b8d6363a408)
你好，出现这个提示的原因是为什么啊？
之后一直显示“发布中，请稍后”，没有上传成功。

**Comment by terwer** [comment]
参考 https://github.com/terwer/siyuan-plugin-publisher/issues/1201 
这个问题还在修复中。。。
