### ISSUE TITLE
csdn平台发布错误-显示添加标签

### ISSUE THREAD

**Issue by 3336840269** [terwer/siyuan-plugin-publisher#1379]
不知道添加标签操作在哪里，怎么弄，能否教导一下，能出个教程就更好了

**Comment by terwer** [comment]
请参考这里面我给了解答：

https://github.com/terwer/siyuan-plugin-publisher/issues/1294

**Comment by 3336840269** [comment]
感谢你的回复，问题已经解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "terwer/siyuan-plugin-publisher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月2日(星期一) 晚上11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [terwer/siyuan-plugin-publisher] csdn平台发布错误-显示添加标签 (Issue #1379)





 
请参考这里面我给了解答：
 
#1294
