### ISSUE TITLE
halo2.X，常规发布，只要选择“分类”就报错

### ISSUE THREAD

**Issue by suosuosi** [terwer/siyuan-plugin-publisher#1387]
一键发布没有问题，因为一键发布默认不选择分类
常规发布如果不选择分类，也不报错
错误信息：
操作失败=>TypeError: ((intermediate value)(intermediate value)(intermediate value) ?? []) is not iterable

分类读取正常，可以看到halo的分类

**Comment by terwer** [comment]
![image](https://github.com/user-attachments/assets/bc1e1d62-c8bc-47d4-8736-d58b1038c21f)

问题无法复现，我是 macos 电脑。

**Comment by terwer** [comment]
可升级到 `v1.30.2`，看看是否已修复。
