### ISSUE TITLE
Wordpress 配置一直出问题

### ISSUE THREAD

**Issue by feewg** [terwer/siyuan-plugin-publisher#1388]
![image](https://github.com/user-attachments/assets/343bf32b-68b3-4301-9a02-4da76e814195)
一直提示这个问题
我确认信息没有问题
或者Wordpress有没有其他配置方法

**Comment by terwer** [comment]
检测一下是不是网络不通。暂时无其他可用信息，有问题欢迎回复。我这边是正常的

![image](https://github.com/user-attachments/assets/b635c146-33a4-41b8-8eea-0d710ab24890)

可参考我的：
https://github.com/terwer/portable-wordpress/
