### ISSUE TITLE
Hexo 如何使用笔记命名作为md文件名，而不是别名

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#1389]
如果给文档设置了多个别名（为了方便查找），发布到Hexo，插件不会使用文档命名而是别名作为文章名，别名如果设置多个，会被空格/逗号截断，导致上传到hexo的文章没有md后缀，文章会发布失败

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by terwer** [comment]
fixed in `v1.29.0`
