### ISSUE TITLE
思源笔记内设置的AI模型不生效

### ISSUE THREAD

**Issue by syc0000000** [terwer/siyuan-plugin-publisher#1392]
“自动提取摘要”等AI功能无法正确通过思源笔记设置页面指定的AI模型请求，始终使用gpt-3.5-turbo
![image](https://github.com/user-attachments/assets/a6d58e96-b960-4b6a-9036-3f7ba838e0df)
思源笔记设置如下
![image](https://github.com/user-attachments/assets/3adb561c-d248-4653-bb49-867565999a65)

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by terwer** [comment]
Fixed in `V1.23.0`
