### ISSUE TITLE
求教：halo 的 API 地址填写的和博客地址一样，请求报错

### ISSUE THREAD

**Issue by idea-zone** [terwer/siyuan-plugin-publisher#1394]
![image](https://github.com/user-attachments/assets/56e248de-d65b-498c-ada7-dd1d3c9ba5bd)

halo 版本 2.20 LTS

**Comment by jayvzh** [comment]
同样问题，新版本出现的问题吗，以前成功过。

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by SenLief** [comment]
同样的问题有解决的方案吗？

**Comment by ssls2026** [comment]
t我这里也同样有这个问题，之前使用过没问题

**Comment by terwer** [comment]
halo:2.9 没这个问题。我试试你们的版本。

**Comment by ssls2026** [comment]
我这里使用的版本是v2.20.8

**Comment by terwer** [comment]
2.20.8确实有这个问题，现在修复。预计今天之内发布。

**Comment by terwer** [comment]
问题已定位修复，原因，官方改了地址：
![image](https://github.com/user-attachments/assets/ff0837ab-a971-4c76-91da-7be280608498)

**Comment by terwer** [comment]
重大调整，由于 Halo 2.20+ 修改了 API 策略，V2.20+ 此平台通过旧的 API已经无法使用，将会新增平台 「Halo网页版」。「Halo网页版」支持 V2.20+，需要导入并重新配置。
如仍需使用此平台，请降级到 Halo 2.9。

V2.20+新平台添加指南：
通用设置->发布设置->插件商店->自定义 HTTP 协议->Halo 网页版

1、添加平台

![image](https://github.com/user-attachments/assets/7997eaab-4b30-4f13-b6c7-c71db5b692cd)

2、设置主页和域名。非常重要。错误将会导致后续鉴权失败

我这里是 http 就写 http，你的如果是 https 的就写 https。看实际地址。

![image](https://github.com/user-attachments/assets/d455dea8-3f49-4e88-b7ed-8c0d925f39ed)

![image](https://github.com/user-attachments/assets/4590b659-7bec-4553-86e6-53c3ec6cebbf)

要注意：
**域名只能是根域名**
**域名只能是根域名**
**域名只能是根域名**

**例如：我的地址是：https://myblog.domain.com:8080/login 或者 https://myblog.domain.com/login**
**或者 https://domain.com:8080/login 或者 https://domain.com/login**
**那么域名只能写：domain.com**
**不能加 /，也不能加端口**

3、开始授权

![image](https://github.com/user-attachments/assets/eea98313-247c-4315-9abe-69a4a618b734)

注：如果上面的地址填写错误可禁用->删除->然后重新导入再填写。

![image](https://github.com/user-attachments/assets/cb7f0662-eb9c-4d88-8791-47f9c258d928)

![image](https://github.com/user-attachments/assets/7ba90d12-5801-414c-9ebd-d1706f1faa00)

![image](https://github.com/user-attachments/assets/f3295dbc-f961-4cad-934d-133f279a93e8)

登录完成点击 xx 关闭即可。

接下来点击验证

![image](https://github.com/user-attachments/assets/433d953f-eb7b-4ee2-94c4-c41495a29ce2)

![image](https://github.com/user-attachments/assets/5935b529-159f-449e-a1ed-abdaae6c6765)


出现这样就完成了。接下来发布就可以了。完结撒花🎉

注意：如果过期了。就点击再次授权，重新登录，重复上面步骤即可。

**Comment by terwer** [comment]
fixed in `V1.22.0`

注意事项：https://github.com/terwer/siyuan-plugin-publisher/issues/1447#issuecomment-2480933827
