### ISSUE TITLE
发布配置页面没有平台的配置

### ISSUE THREAD

**Issue by itmanmax** [terwer/siyuan-plugin-publisher#1395]
![image](https://github.com/user-attachments/assets/881a505f-de82-4c19-9fb9-34d170ab2000)
![image](https://github.com/user-attachments/assets/da96c487-4354-475a-afe0-e0f296c8175a)
为什么导入平台之后配置页面没有平台的配置，我的是服务器的docker配置的，我pad上就可以显示

**Comment by terwer** [comment]
请看 faq5，地址应该没对

https://blog.terwer.space/s/20230810132040-nn4q7vs

**Comment by itmanmax** [comment]
看见了，不好意思，没配置思源地址
