### ISSUE TITLE
操作失败=>Error: Invalid XML-RPC message

### ISSUE THREAD

**Issue by itmanmax** [terwer/siyuan-plugin-publisher#1396]
发布到Typecho显示报错：操作失败=>Error: Invalid XML-RPC message
![image](https://github.com/user-attachments/assets/1813ae99-fc9b-4072-b703-de6a02013117)
但是实际上已经发布成功的了：
![image](https://github.com/user-attachments/assets/9a801457-0b8a-4d19-86ab-2e2083a57c3b)
是我的Typecho还是哪里有错误吗

**Comment by terwer** [comment]
看看 typecho 的后台日志。这种是博客后台报错
也可以看看这里 https://ld246.com/article/1693750229584

**Comment by itmanmax** [comment]
> 看看 typecho 的后台日志。这种是博客后台报错 也可以看看这里 https://ld246.com/article/1693750229584

typecho 的后台日志哪里看，我怎么没有呢
![image](https://github.com/user-attachments/assets/b50338d9-612e-4457-bfcf-d41cf2c42178)      
 这里 https://ld246.com/article/1693750229584 我看了，好多和我一样错误的人，说可以试试安装xml拓展，
![image](https://github.com/user-attachments/assets/6743bc7c-063b-4cdc-89b6-1289c4323082)
但是安装了还是报错不知道为什么

**Comment by itmanmax** [comment]
难道看看服务器请求吗？

**Comment by terwer** [comment]
这种是 typecho 服务器本身的问题和插件无关，请求抓包一下也是比较好的排查手段。

**Comment by itmanmax** [comment]
> 这种是 typecho 服务器本身的问题和插件无关，请求抓包一下也是比较好的排查手段。

额，不太会，。。。。

**Comment by terwer** [comment]
https://github.com/terwer/portable-typecho
我用这里的脚本，官网下载的 
https://github.com/typecho/typecho/releases/latest/download/typecho.zip
扔进去直接解压

![image](https://github.com/user-attachments/assets/879e8cde-423c-43a1-ba29-cc989cd80b1d)

```
docker compose up --build
```
![image](https://github.com/user-attachments/assets/fde85fb3-67d4-4657-a7e7-15bbc121cefe)

![image](https://github.com/user-attachments/assets/f6ff46d7-f50c-4c5e-9ce2-44f755bc7f1d)

![image](https://github.com/user-attachments/assets/034eed63-c20e-4e8a-97a3-30ed69119d42)

![image](https://github.com/user-attachments/assets/631daf53-621b-42c0-bcb2-10a481abf367)

![image](https://github.com/user-attachments/assets/7e3be240-826b-4eae-9469-fcbb4b7cb0f7)

没发现异常，你检查下是不是少了什么组件或者其他插件引起的。无法复现问题，先关闭了。

如有其他问题：QQ群-722632752

[![](https://img.shields.io/badge/QQ群-722632752-blue)](https://qm.qq.com/cgi-bin/qm/qr?k=Knb4_xp6bbPnTpMztzqIZI7v59Gblqoh&jump_from=webapi&authKey=IhivNiJsNHq0I0Z+3jyBfOQPxsvMu9Y5jY5FuVTwjtQ5qtjW0m+hpSMsBCu5A8EE)

**Comment by itmanmax** [comment]
看了一下后台报错日志，是edit.php有空值，因为大家肯定不是用的官方的主题，所以每个主题下面的细节也就不愿意，报错就是说edit.php里面说传递了空的标签，改一下就好了，谢谢啦
