### ISSUE TITLE
Halo 2.20 仍然无法使用

### ISSUE THREAD

**Issue by jayvzh** [terwer/siyuan-plugin-publisher#1423]
![微信截图_20241114112729](https://github.com/user-attachments/assets/8860a747-21be-4999-b6e5-5e33a5f2fb7c)
全部里面的common_Halo API授权报错如上。
halo版本：2.20.7 升级到 2.20.9 都试了，相同报错
插件版本：已升级到最新v1.23.0 但底部版权仍显示 v1.21.6 也删除重装过 以及github下载替换过

**Comment by terwer** [comment]
common_Halo 只能用 halo 旧版本，新版本需要使用 halo 网页版

https://github.com/terwer/siyuan-plugin-publisher/issues/1394

**Comment by jayvzh** [comment]
> common_Halo 只能用 halo 旧版本，新版本需要使用 halo 网页版
> 
> #1394

halo 网页版 网页授权页面空白什么原因？试了多次
![微信截图_20241115100237](https://github.com/user-attachments/assets/d592a91b-6856-44e3-8a4f-21ac231453c5)

**Comment by terwer** [comment]
你的地址配置不正确啊，请仔细阅读上面的教程 https://github.com/terwer/siyuan-plugin-publisher/issues/1394

**Comment by jayvzh** [comment]
好吧原来是这样：登录地址要配置全包含协议，域名只写域名
http://xxx.xx/login
xxx.xx
