### ISSUE TITLE
halo 网页版无法授权

### ISSUE THREAD

**Issue by hdd1024** [terwer/siyuan-plugin-publisher#1447]
- 笔记系统：macos
- 思源版本：v3.1.11
- 插件版本:v1.24.0
- halo版本：2.20.9
在发布插件中添加 halo 网页版本授权，点击授权一直是空白页，无法授权
<img width="381" alt="image" src="https://github.com/user-attachments/assets/b3c1f46a-4beb-49e5-b137-836b146e4f68">

<img width="899" alt="image" src="https://github.com/user-attachments/assets/839c9ea7-3486-4aea-9ae4-d2a18aea49e5">

**Comment by hdd1024** [comment]
补充：主域名填写过：www.test.cn、test.cn 都没有授权成功，弹出的窗口也空白页

**Comment by hdd1024** [comment]
该问题已解决，主要是地址没填对。参考：https://github.com/terwer/siyuan-plugin-publisher/issues/1394#issuecomment-2461651525

**Comment by terwer** [comment]
1、登录地址必须是是全路径，不能以/结尾， 例如：`http://localhost:8090/login`
2、域名不带端口、不带 https、https，例如：`localhost`
若有其他问题可回复。
