### ISSUE TITLE
发布到halo的文章，目录总是跳转文章顶部

### ISSUE THREAD

**Issue by hdd1024** [terwer/siyuan-plugin-publisher#1452]
插件将笔记发布到到halo，发现点击目录中的条目总是跳转到文章顶部。
halo维护成员回复，是因为发布的文章没有向 heading 添加 id。具体可以看下面链接
https://github.com/halo-dev/halo/issues/7046#issue-2667317792

**Comment by terwer** [comment]
fixed in `v1.25.0`
