### ISSUE TITLE
halo2.20 picgo图床支持

### ISSUE THREAD

**Issue by syc0000000** [terwer/siyuan-plugin-publisher#1461]
当前使用halo web方式上传文档时，不支持选择picgo作为图床，只能内置。
可能是因为通过模拟网页的方式提交文章不支持图片外链，能否像halo 2.19一样采用api方式提交。
api：https://api.halo.run/
认证方式有改变：https://docs.halo.run/developer-guide/restful-api/introduction#%E4%B8%AA%E4%BA%BA%E4%BB%A4%E7%89%8C%E6%8E%A8%E8%8D%90

**Comment by terwer** [comment]
fixed in `v1.25.1`
