### ISSUE TITLE
关于删除

### ISSUE THREAD

**Issue by Gwyn-S** [terwer/siyuan-plugin-publisher#1500]
能加个 通过插件强制删除后同步将仓库中的也一并删除 的功能吗

**Comment by terwer** [comment]
删除功能就是同步将仓库中的也一并删除啊。

强制删除只是删除引用，而且强制删除一般是用在，远程已经删除了本地有残留的情况。其他情况请使用【取消】，取消就是删除的意思。

**Comment by Gwyn-S** [comment]
感谢回答，但是现在使用下来发现图片不能一并删除了，是因为我使用的是思源上传的吗，没有用picGo

**Comment by terwer** [comment]
图片不支持删除。因为你没法知道图片是哪里来的。在平台上，比如博客园。你删除文章。图片也是不会级联删除的。图片这种一般就是持久化的。
