### ISSUE TITLE
AI设置的baseurl的格式是什么

### ISSUE THREAD

**Issue by itmanmax** [terwer/siyuan-plugin-publisher#1501]
https://api.gptgod.online/
https://api.gptgod.online/v1/
/v1/chat/completions 
哪一种，我试了都不太对
![image](https://github.com/user-attachments/assets/a539aa7b-d955-4d22-8097-0ab13ac0b3f7)

**Comment by terwer** [comment]
就是思源笔记自身的配置 https://api.openai.com/v1 

![image](https://github.com/user-attachments/assets/53a84c1e-4951-4910-99e3-07114b471d52)

**Comment by itmanmax** [comment]
![Screenshot_2024-12-03-09-56-31-153_org b3log siyuan](https://github.com/user-attachments/assets/5f161928-e56e-4916-be4a-174584c44505)
为什么这个不能用呢

**Comment by terwer** [comment]
请先用标准的 chatgpt api 测试。其他厂商不保证能用

**Comment by itmanmax** [comment]
> 请先用标准的 chatgpt api 测试。其他厂商不保证能用

额 标准的有点贵捏，目前没有，好吧

**Comment by itmanmax** [comment]
我这个是oneapi的

**Comment by terwer** [comment]
只要是兼容 open api 接口的一般都能用。但是具体问题就看接口提供商了。其实具体错误可以去开发者工具看网络请求的
