### ISSUE TITLE
hexo 发布，使用图床失败

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#1502]
![PixPin_2024-12-02_22-34-16](https://github.com/user-attachments/assets/c34d95c4-df93-4c5f-82fe-232137df38c0)

已经上传到图床了，之前版本可以正常上传，更新了v1.29.2之后无法上传图床

**Comment by terwer** [comment]
开发者工具看一下错误日志发出来看看

**Comment by terwer** [comment]
fixed in `v1.29.3`

**Comment by Achuan-2** [comment]
好嘞，辛苦大佬

**Comment by IceDragonFla** [comment]
抱歉打扰，请问一下Achuan大佬，您是如何将本地图片转化为图床图片的呢。是使用picgo嘛。我现在遇到了一个问题：我想要将siyuan文件同步到hexo中，但是因为siyuan内的图片文件为本地路径，picgo上传图床后无法将图片路径修改。

**Comment by Achuan-2** [comment]
> 抱歉打扰，请问一下Achuan大佬，您是如何将本地图片转化为图床图片的呢。是使用picgo嘛。我现在遇到了一个问题：我想要将siyuan文件同步到hexo中，但是因为siyuan内的图片文件为本地路径，picgo上传图床后无法将图片路径修改。

使用这个插件，就可以直接把图片上传到图床，并同时发布文章到hexo了，我设置的是思源笔记里的图片路径依然是本地路径，只有发布时替换为图床路径，这样做是为了避免因为图床失效导致图片丢失，图片也可以进行裁剪编辑标注和修改替换

**Comment by IceDragonFla** [comment]
> > 抱歉打扰，请问一下Achuan大佬，您是如何将本地图片转化为图床图片的呢。是使用picgo嘛。我现在遇到了一个问题：我想要将siyuan文件同步到hexo中，但是因为siyuan内的图片文件为本地路径，picgo上传图床后无法将图片路径修改。
> 
> 使用这个插件，就可以直接把图片上传到图床，并同时发布文章到hexo了，我设置的是思源笔记里的图片路径依然是本地路径，只有发布时替换为图床路径，这样做是为了避免因为图床失效导致图片丢失，图片也可以进行裁剪编辑标注和修改替换

请问大佬有具体的实现方式嘛，是直接在publisher插件里面设置图片的上传方式嘛，还是在picgo插件里面呢。
另一个问题是您使用的是github action进行部署的嘛 非常感谢大佬TAT
