### ISSUE TITLE
Ai文章摘要completions请求没有指定模型

### ISSUE THREAD

**Issue by fanlisboy** [terwer/siyuan-plugin-publisher#1508]
![image](https://github.com/user-attachments/assets/d107a97f-3c0e-4ed4-b43c-4462e8cf20ce)
如上图所示
思源AI有配置模型
![image](https://github.com/user-attachments/assets/39d6b18c-be71-48f6-a64e-134963b69743)
插件版本：v1.29.3

**Comment by terwer** [comment]
![image](https://github.com/user-attachments/assets/c60e9156-ee04-489b-9f00-851a476979ab)

未能复现。更新最新版再试试
