### ISSUE TITLE
常规发布一直卡在页面上没反应

### ISSUE THREAD

**Issue by 834116404** [terwer/siyuan-plugin-publisher#1520]
![image](https://github.com/user-attachments/assets/3628b27a-d143-42dd-ae32-b341ce7c1537)

**Comment by 834116404** [comment]
发现了, 原来是太慢了...
![image](https://github.com/user-attachments/assets/4b8e49d2-7dda-400e-b983-0e62c83259e2)

**Comment by 834116404** [comment]
发现了, 原来是太慢了...
![image](https://github.com/user-attachments/assets/4b8e49d2-7dda-400e-b983-0e62c83259e2)

**Comment by terwer** [comment]
未能复现问题
