### ISSUE TITLE
发布失败

### ISSUE THREAD

**Issue by 834116404** [terwer/siyuan-plugin-publisher#1522]
操作失败=>Error: forward request failed: Post "https://api.terwer.space/api/prismjs": context deadline exceeded (Client.Timeout exceeded while awaiting headers)  提升这个

**Comment by 834116404** [comment]
![image](https://github.com/user-attachments/assets/69230396-9d2b-47e8-b831-8a7366d21dba)

**Comment by terwer** [comment]
代码块用了这个共享 api 去渲染，为了和 csdn 保持一致，你那里不能访问 https://api.terwer.space/api/prismjs 这个 API 吗？这个是部署在 vercel 上的服务。

**Comment by 834116404** [comment]
> 代码块用了这个共享 api 去渲染，为了和 csdn 保持一致，你那里不能访问 https://api.terwer.space/api/prismjs 这个 API 吗？这个是部署在 vercel 上的服务。

可能是我这边公司网络有卡控吧
