### ISSUE TITLE
hexo使用已有的分类时，点击复选框，发布报错。

### ISSUE THREAD

**Issue by itian932** [terwer/siyuan-plugin-publisher#1529]
在进行hexo平台发布文章时，选用已有的分类，如果是点击复选框选中的话，会报 操作失败=>TypeError: ((intermediate value)(intermediate value)(intermediate value) ?? []) is not iterable v103.1.10；但是点击文本内容选中的话就没有问题。

![image](https://github.com/user-attachments/assets/5ec3fb38-70f5-4273-bf2b-ce9e73d0a2b4)

**Comment by itian932** [comment]
希望作者大大稍微修复一下，谢谢！

**Comment by terwer** [comment]
fixed in `v1.30.2`
