### ISSUE TITLE
hexo深度适配

### ISSUE THREAD

**Issue by terwer** [terwer/siyuan-plugin-publisher#452]
- ~~高亮块以及其他自定义标签~~
https://github.com/ppoffice/hexo-theme-icarus/discussions/1187
https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/0132965ca3204761a2b0e89a29ec4979aa914cb6/source/_posts/zh-CN/Custom-Hexo-Tag-Helpers.md
https://ppoffice.github.io/hexo-theme-icarus/uncategorized/%E8%87%AA%E5%AE%9A%E4%B9%89hexo%E6%A0%87%E7%AD%BE%E6%8F%92%E4%BB%B6/#tab_icon_2

MD没有标记，暂时不好实现

**Comment by Chenm4** [comment]
请问一下hexo那个文章开头会有用---框起来的东西，这个能让我们自定义吗

**Comment by terwer** [comment]
最新版本已经支持源码模式修改了。或者你还有别的交互方式吗，暂时还没有想好该怎么去做自定义。

![图片](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/6c7d74cb-f6a7-4007-a4f7-f3bc01ff65f2)

**Comment by terwer** [comment]
yaml编辑问题已修复。其他的只能说不好适配，先关闭。
