### ISSUE TITLE
挂件的浅色模式下，按钮提示框显示异常

### ISSUE THREAD

**Issue by OriOYue** [terwer/siyuan-plugin-publisher#453]
如图：
![image](https://user-images.githubusercontent.com/72482686/227820012-76979ee3-c285-4abf-80b7-3989f88faae2.png)
切换默认主题daylight也是如此，
当然挂件的暗黑模式是正常的。
版本：0.8.0

**Comment by terwer** [comment]
目前检测到情况如下：
1、系统是显色模式，这样挂件浅色、深色都没问题。
2、系统是深色模式，挂件强制浅色模式显示如作者所示。

请问：您确实是有在电脑深色模式的情况下用浅色模式的需求吗？

**Comment by OriOYue** [comment]
确实有这个需求，因为我的思源的外观模式是没有设置跟随系统的，而系统是常年暗黑模式。
所以挂件的外观可以适配思源的外观模式吗？毕竟思源和挂件是一体的。感谢！

**Comment by terwer** [comment]
好的，下版本修复。

**Comment by terwer** [comment]
已升级最新插件，此单不再适用。新问题可重写提单。
