### ISSUE TITLE
hexo 不能设置分类categories

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#486]
一般习惯用categories分大类，标签用来辅助

**Comment by terwer** [comment]
是的，这个是我下版本重点支持的特性。敬请期待！
另外FrontFormatter 设置也打算更好支持。
目前WordPress、博客园这些是支持分类的。

**Comment by Achuan-2** [comment]
好滴，感谢！非常期待

**Comment by terwer** [comment]
插件版1.9.0已发布，支持分类、标签、摘要、YAML自定义等，稍后可在集市下载。
