### ISSUE TITLE
hexo permalink无法关闭

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#489]
hexo的博客配置里，我已经用了Hexo-abbrlink插件来生成永久固定链接，所以希望发布工具本身就不要生成permalink了
目前发现即使关闭了永久链接按钮，yaml还是会产生permalink
另外想问问一些选项能否默认配置呢，比如hexo中默认设置yaml中date开启
![image](https://user-images.githubusercontent.com/60436214/235113287-6ff03769-8043-4221-8d1c-0d5a22b47043.png)

![image](https://user-images.githubusercontent.com/60436214/235113121-3e124815-07d9-4083-af34-af30a9c9c7fd.png)

**Comment by terwer** [comment]
插件版1.9.0已支持自定义修改YAML。可在集市下载最新版本。
