### ISSUE TITLE
大佬考虑增加发布到知乎和CSDN吗

### ISSUE THREAD

**Issue by kindfaker** [terwer/siyuan-plugin-publisher#507]
虽然CSDN是垃圾堆，但是┐(ﾟ～ﾟ)┌平时还是用这个比较多，看到大佬有发布博客园的功能，希望也能出一个发布到知乎和csdn的功能

**Comment by terwer** [comment]
考虑加，敬请期待！

**Comment by terwer** [comment]
知乎已经支持。CSDN因为接口体重，需要一段时间调研。

**Comment by terwer** [comment]
1.12.0 已全部支持
