### ISSUE TITLE
MacPro m1 思源v2.9.8 显示不兼容

### ISSUE THREAD

**Issue by yarzzc** [terwer/siyuan-plugin-publisher#541]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/98455501/04b4049a-76ca-44d9-96a3-3d4a83ad8018)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/98455501/7f0faab1-ebc9-4f37-aac9-9578c90a818f)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/98455501/22c3847e-8564-477c-9d4e-5b42c9634da2)
左上角小飞机图标无法展示，无法使用发布功能，以前曾使用过挂件，已删除挂件，清除所有自定义JS，删除插件重新下载依然无法正常使用

**Comment by yarzzc** [comment]
1. 删除插件退出思源
2. 重新下载插件出现小飞机图标
3. 删除设置里原有不生效配置
4. 目前暂且正常

**Comment by yarzzc** [comment]
保存后，思源笔记重新渲染，插件不兼容

**Comment by terwer** [comment]
修复了一下，下午可关注下 1.2.2 是否修复。
