### ISSUE TITLE
请问插件版支持图床替换图片了吗

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#593]
非常感谢作者制作的插件，很强大，比心❤

想问问目前插件版 v1.6.0 支持图床替换图片了吗，目前插件内配置github图床，并且上传文章图片到图床，可是文章上传到其他平台，图片链接依然是本地

**Comment by terwer** [comment]
前期主要是基础功能，现在基本完毕，后续会持续完善其它细节。
图床功能还没加，正在紧锣密鼓的准备，预计下版本加上。
另外 hexo 的自定义属性也会在下版本加上。

**Comment by Achuan-2** [comment]
好的，辛苦！

**Comment by terwer** [comment]
已支持替换图片。但是个别平台不能用，需要使用自己的上传逻辑，比如知乎、Notion，这个下版本继续完善。
目前替换图床链接可以生效的平台有：语雀、Hexo、博客园、Typecho、WordPress。
下午可升级1.7.0

**Comment by Achuan-2** [comment]
好的，谢谢
