### ISSUE TITLE
增加Docker兼容

### ISSUE THREAD

**Issue by SenLief** [terwer/siyuan-plugin-publisher#633]
<img width="680" alt="111" src="https://github.com/terwer/siyuan-plugin-publisher/assets/31976451/77553883-ec94-4a5f-8d2c-c2f3f806bceb">
以前的时候这个填写的内容都是自动的。现在是要填写什么东西吗

**Comment by terwer** [comment]
删除重新添加吧。需要显示指定子平台。目前仅支持Hexo，后续会支持其他平台。

**Comment by SenLief** [comment]
> 删除重新添加吧。需要显示指定子平台。目前仅支持Hexo，后续会支持其他平台。

卸载好像没有卸载干净。重新安装不行。

**Comment by terwer** [comment]
平台禁用之后可以删除这个平台的配置

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/6017509c-3ee3-4c02-b24b-2f10d3bbff63)

如果还有问题可再次提出

**Comment by SenLief** [comment]
我没有平台出现，现在卡在添加这里了。

**Comment by terwer** [comment]
请备份 [workspace]/data/storage/syp/sy-p-plus-cfg.json ，然后删除，这个配置文件会在第一次使用时自动初始化。

**Comment by SenLief** [comment]
我在mac上使用是成功的，但是在docker版本上使用不成功，体现还是找不到子平台，这个主要是不知道如何调试，上面mde文件删除也已经是做了的，还是不行，可能是docker兼容性不好吧。

**Comment by terwer** [comment]
docker未做兼容测试。建议使用PC客户端。

**Comment by terwer** [comment]
精力有限，建议使用 使用PC客户端 ，后续不再支持其他客户端。

**Comment by terwer** [comment]
作为长期计划，慢慢更加 docker 支持。

**Comment by terwer** [comment]
https://github.com/terwer/siyuan-plugin-publisher/issues/846
这里跟踪。
