### ISSUE TITLE
配置验证通过，发布博客失败，hexo

### ISSUE THREAD

**Issue by luommy** [terwer/siyuan-plugin-publisher#661]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/ab23bbcb-fb9e-4429-8515-1abcb659c317)

**Comment by terwer** [comment]
hexo 的分支和目录必须正确。默认是main分支。如果不是main，请展开修改更多配置修改。
存储目录默认是仓库下面的 source/_posts。如果是自定义也请自行修改。
如果不清楚hexo默认的仓库目录格式，可参考 https://github.com/terwer/hexo-blog

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/c94e9902-2777-47b7-8267-712a6fc41ba6)


![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/8ee44236-2e7d-45fa-a67e-7885d6a2767d)

**Comment by terwer** [comment]
先关闭了，有问题继续跟帖。

**Comment by luommy** [comment]
[目前的情况：]

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/47832748-96a5-45dd-83b2-de4dbbf63588)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/c35611f3-e638-4d87-adf8-23b9d3a42012)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/22f12436-f909-41cb-b7e9-c3481db28c7d)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/f3e79f1b-2acf-4fd0-a9a6-7413fe1f5eb4)

我手动在仓库下补的source/_posts 还是不行呀o(╥﹏╥)o

**Comment by luommy** [comment]
补充信息，在本地项目下我添加了md格式文件后，使用hexo g 部署文章目录就这样了：

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/147ac303-d6a5-4d80-a36e-2164dd105874)

**Comment by terwer** [comment]
我这个支持的是源码目录，直接发布MD的，不是发布构建后的内容。插件只负责MD的传输，不负责构建部分。

**Comment by terwer** [comment]
你看我的仓库就知道了 https://github.com/terwer/hexo-blog

只支持源码部署，只支持源码部署，只支持源码部署。

另外
如果配置异常，请备份 `[workspace]/data/storage/syp/sy-p-plus-cfg.json` ，然后删除，这个配置文件会在第一次使用时自动初始化。

**Comment by luommy** [comment]
这次我用你的构建了，这样：
目录也是保持一致的 还是不行
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/fde119b2-d5f4-412d-8264-0bc4fa91af4b)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/a2069b72-6f2f-45aa-a8df-f1a09ece5eff)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/3cadf4ff-3d99-4a93-a3a4-53dd53f969ed)

**Comment by terwer** [comment]
你用的是PC客户端吗。目前 **仅支持PC客户端** ，其他设备比如浏览器、docker、等均不支持。

如果配置异常，请备份 [workspace]/data/storage/syp/sy-p-plus-cfg.json ，然后删除。这个尝试了吗。

我这里没有出现你说的问题。

如果是PC客户端，打开开发者模式，切换到network，可以看看请示失败的请求信息。否则没法排查

**Comment by luommy** [comment]
是的 PC客户端

配置没有出现过异常（具体情况是：本来配置是好的，备份那个json文件后我尝试删掉，然后它第一次打开初始化新生成json再建立一个新的发布设置就会出现配置异常，我立马把备份恢复了，那个配置异常就没有显示了）

明天我打开开发者工具看看是否有更多的请求失败的信息~

**Comment by luommy** [comment]
补充：

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/4e6591aa-71ac-47e3-8d0e-c7d611eabae6)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/948fb23e-82c9-4a41-ae81-f35647f3893c)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/9c7a0b3f-64b0-46bf-85af-944eb381d3f0)

这些错误信息

**Comment by terwer** [comment]
路径配错了
<img width="338" alt="图片" src="https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/32b727eb-7247-40ec-b6ed-5136d2dc4518">

正确的应该是

<img width="244" alt="图片" src="https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/80725b00-b258-4fd3-9171-28a78ba128b0">

hexo的设置里面可以看到。如果你用我的模板添加不应该出错。其实你看看仓库的目录就知道的这个目录你配错了。你应该是自己改错了。

<img width="410" alt="图片" src="https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/1ae7cb31-e021-4995-affe-1cc077407adc">

<img width="323" alt="图片" src="https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/d8744986-611f-4cce-991f-d750fc2b9f60">

<img width="845" alt="图片" src="https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/416ebe86-d6b5-4239-b167-44bddb914c45">


<img width="700" alt="图片" src="https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/988c90d8-08a8-4208-8021-6aff6dd1fb21">

**Comment by luommy** [comment]
好奇怪呀
我这边配置的是没问题呀：这个source/_posts
但是为何发起put请求的时候多了“contents”
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/a6dee567-52da-4c18-bc3f-6b68b13ab5c6)

我仓库确实也是用的你的，没有改：
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/5cfab0e3-a638-4007-b370-8d94797e58c8)

**Comment by terwer** [comment]
配置点了保存吗，没保存的话可能是之前的残留。
或者你直接手动在 [workspace]/data/storage/syp/sy-p-plus-cfg.json 搜索，然后修改。配置修改之后要点击保存按钮。这个配置存文件，所以必须点击保存按钮。
我这没出现你这个问题。

**Comment by luommy** [comment]
点击保存了，配置文件中也能搜索到对应的账户，但是sy-p-plus-cfg.json 配置文件中也没有搜索到“contents”字样，不知道为何

发布的时候多了contents，然后我将之前的发布配置停用了

又新建了一个发布配置，这次是新的问题，账户验证也是通过的，github生成的tokens在配置文件中也能查到，但是发布显示：

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/72eb3e82-678d-460d-b47b-7cda30debbf0)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/784056ba-9d29-480e-a977-478e78168037)

…………又尝试了下，应该是不能用新的beta-token，用classic-token是没问题的，我刚才新建的那个发布配置是用的beta

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/1e1e9e2e-9988-4e5e-98a0-ce3867c3884b)

但问题还是老问题，不知道为啥多了"contents"，配置应该是保存的了，不然在配置中搜索不到tokens：

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/04331530-8d19-4a8b-bc8f-a00b05692f80)

**Comment by terwer** [comment]
旧的配置删除吧，光禁用没用的。禁用只是更改状态，脏数据还在。

token确实是不支持beta

**Comment by luommy** [comment]
已经删除了旧的配置，还是一样的：

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/e1d9a5ab-6fab-4db7-b56d-da358a8f8cfa)

**Comment by terwer** [comment]
sy-p-plus-cfg.json 文件备份下删除，用模板添加。你这一看就是旧配置啊。或者加下我qq 1035136784。这个问题，折腾几天，我都感觉太费劲了 [手动狗头]

**Comment by luommy** [comment]
哈哈哈 确实，我把json配置文件备份删除后，新初始化生成的json配置还是有旧配置的记录，我尝试卸载下插件重新装下

**Comment by terwer** [comment]
等会，你应该是工作空间搞错了吧。卸载重装不影响配置文件的。因为这些配置是重要信息，卸载不会主动删除，我觉得应该是你工作空间搞错了。
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/a64f28bc-f502-4c9a-af02-3e0906c7ae89)

这里打开工作空间，如果有多个空间看看不是不搞错了。另外，**最好先关闭思源笔记，然后删除配置，再打开** 。防止打开状态下数据已经读取了。

**Comment by luommy** [comment]
我的空间是这样的： 在工作空间下 有另一个工作空间，

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/97df598c-080c-4713-9072-48c20697af76)

我删除的配置文件也是另一个工作空间的json文件，也就是这个，应该是没错的：

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/feb00c0b-ff3f-44b2-97a3-78a35584186a)

**Comment by terwer** [comment]
你这用法很不常规啊。最简单的都删了看看。没生效应该就是搞错了。

**Comment by luommy** [comment]
我都删除掉了，创建了一个新的工作空间，但是好像发布加载不出来了，同时我看那个配置文件sy-p-plus-cfg.json在新的工作空间下也没有初始化自动生成：

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/b6318e0a-5cdc-44a1-824b-f0294657ee79)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/838dd37e-d60a-4e0e-b3be-6ab960daaff0)

**Comment by terwer** [comment]
我们私聊吧，解决速度快

**Comment by terwer** [comment]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/46d59566-f2de-4e12-a786-c3a5c32f2f80)

你试试先打开发布配置，不要先进入发布页面。因为没有配置发布页面用不了。

**Comment by luommy** [comment]
配置没问题的，就点发布就没有页面了：

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/2d6fa0ef-16f4-4ce3-a5b4-5d44fe4c8608)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/51da2c8b-bc8c-40a0-ba5c-cef776b3bd77)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/f8f5da6a-1a5c-4b65-ac81-9a54a322b608)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72240631/f6948541-a0d0-4ab3-a71c-15327180df9f)

**Comment by luommy** [comment]
我加你V吧 我这边登录不上Q

**Comment by terwer** [comment]
> 我加你V吧 我这边登录不上Q

hiterwer 我微信
