### ISSUE TITLE
Typecho 图片 视频加载失败

### ISSUE THREAD

**Issue by fengwind2006** [terwer/siyuan-plugin-publisher#695]
发布到typeecho问题
与siyuan-plugin-blog插件问题一致，
![屏幕截图 2023-09-01 102903](https://github.com/terwer/siyuan-plugin-publisher/assets/91138941/71a52d0a-1857-46f9-85c2-68289ea70172)
图片路径错误，导致无法加载
![屏幕截图 2023-09-01 103053](https://github.com/terwer/siyuan-plugin-publisher/assets/91138941/76f5aa9a-d1de-4473-bab6-8c7a0b3c676e)
视频路径错误，导致无法加载

**Comment by terwer** [comment]
图片目前已经支持自动上传了，更新到最新版试试。最新版本是1.11.3，建议先卸载，在更新。
我刚刚测试Typecho图片是可以的。
http://blog.terwergreen.com:8007/index.php/archives/30/

视频暂时无法支持。视频占用资源较大，建议嵌套使用第三方视频网站链接。blog插件因为是在笔记内部，所以适配链接是可以修复解决的。而发布是需要吧视频文件上传到平台，这个基于性能问题，暂时不支持。

**Comment by terwer** [comment]
另外，对于Typecho，如果使用了我的Picgo插件，会使用图床，否则会使用Typecho自带的图片上传。

**Comment by fengwind2006** [comment]
> 图片目前已经支持自动上传了，更新到最新版试试。最新版本是1.11.3，建议先卸载，在更新。 我刚刚测试Typecho图片是可以的。 http://blog.terwergreen.com:8007/index.php/archives/30/
> 
> 视频暂时无法支持。视频占用资源较大，建议嵌套使用第三方视频网站链接。blog插件因为是在笔记内部，所以适配链接是可以修复解决的。而发布是需要吧视频文件上传到平台，这个基于性能问题，暂时不支持。

请问有办法直接调用伺服端思源的资源文件吗，这样就不需要上传了。
