### ISSUE TITLE
HttpError: Invalid request. "sha" wasn't supplied.

### ISSUE THREAD

**Issue by muxinxy** [terwer/siyuan-plugin-publisher#754]
平台：Github Hexo
操作：为了更新文章，用“插件”发布一篇“挂件”发布过的笔记
问题：HttpError: Invalid request. "sha" wasn't supplied.
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/32673109/6b4397e6-4cd8-4270-a6c4-c427d2a2fe9f)

**Comment by terwer** [comment]
已修复，容错策略如下：
在首次创建文件失败时，尝试删除旧文件，然后再次尝试创建新文件。如果再次创建新文件仍然失败，它会抛出一个异常。最后，它返回最后一次请求的结果。
请升级 `1.17.0`
