### ISSUE TITLE
Halo 平台无法设置发布时间

### ISSUE THREAD

**Issue by mdzz2048** [terwer/siyuan-plugin-publisher#765]
思源里在插件界面可以设置发布时间

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/86549958/75a66a44-0c9e-4680-a021-35c94199556a)

但是发布后显示的是更新时间

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/86549958/179939f3-ff11-4cf1-a8bf-b24e30733482)

**Comment by terwer** [comment]
已修复，请升级 `1.17.0`
