### ISSUE TITLE
思源 v2.10.9 dev3 picgo图床无法显示

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#771]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/60436214/ff211259-4ca3-4a51-a792-785b40c5f91b)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/60436214/4b74c543-53c5-4346-8f9e-ebbdcbf4c80a)

**Comment by terwer** [comment]
已修复，请升级 Picgo 插件到 `1.5.1`

参考：[PicGO与最新版思源笔记的兼容问题](https://github.com/terwer/siyuan-plugin-picgo/issues/164)
