### ISSUE TITLE
发布偏好设置每次打开思源都会被重置，无法保存

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#773]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/60436214/c26677e9-aaf8-4df3-8485-2122b4b32ee2)

**Comment by terwer** [comment]
嗯，这部分没有持久化。是个已知问题，我在考虑要不要调整。其他配置目前是持久化到json文件的。

**Comment by Achuan-2** [comment]
应该持久化吧，毕竟更改这种设置都是用户习惯，标题编号、去除正文H1这种，一般情况下都是统一设置的

**Comment by terwer** [comment]
确实应该，之前一是偷懒，二是感觉这个不是很常用。下版本会改成持久化的。

**Comment by terwer** [comment]
已适配。存储位置如下：

`[dataDir]/storage/syp/[xxx.json]`

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/7e8e31ca-82a2-4523-b104-828accaead5e)

请升级 `1.7.0`

**Comment by Achuan-2** [comment]
好滴，辛苦
