### ISSUE TITLE
发布到知乎不支持表格嘛

### ISSUE THREAD

**Issue by cesaryuan** [terwer/siyuan-plugin-publisher#774]
如题，我有一篇文章，发布到知乎，但是所有的表格都不见了

https://zhuanlan.zhihu.com/p/660582882

https://cesaryuan.top/post/what-should-i-do-if-conda-is-too-slow-use-mamba-instead-of-turtle-speed-conda-z1oondz

**Comment by terwer** [comment]
知乎表格格式比较严格，已经适配。下版本修复。

**Comment by terwer** [comment]
https://github.com/terwer/siyuan-plugin-publisher/pull/777

已支持，请升级 `1.16.0` 。文章需要重新更新一次。
