### ISSUE TITLE
请求错误，请在偏好设置配置请求地址和ChatGPT key！

### ISSUE THREAD

**Issue by xiaoyi510** [terwer/siyuan-plugin-publisher#799]
请求错误，请在偏好设置配置请求地址和ChatGPT key！

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/20254874/978ed873-dfa4-4f0c-9430-9e3dc53ab16f)

实际已经配置

**Comment by terwer** [comment]
![9253ba101b3b217b81613853f201adbe](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/56c4adfb-ab1b-486c-8ff2-fd15aaf09739)

目前仅支持这种配置。而且第一次如果不行，多试几次看看。有时候ai网络问题或者key到期的情况，也是这个通用错误提示。

**Comment by terwer** [comment]
先关闭了，有其他问题欢迎回复。

**Comment by xiaoyi510** [comment]
我填写的都是官方的,,,,key现在也正常使用

**Comment by terwer** [comment]
官方的可能需要自己搭建梯子。
注意：我这里没有使用思源笔记的代理设置。API请求都是直连的。所以用官方的话你本地可能需要自己搭建梯子。
另外，可能需要提供更多配置界面截图看看问题。检测到配置只是说明配置不为空，不代表配置可用。
我这用的第三方，一直是可用的。

**Comment by Achuan-2** [comment]
填了网络代理就会报这个错误，我不填就没问题
