### ISSUE TITLE
发布配置中的`文件规则`无法手动设置

### ISSUE THREAD

**Issue by VxRain** [terwer/siyuan-plugin-publisher#800]
之前使用挂件版的时候，`Hugo` 平台中的文件规则可以设置为[filename].md，这样发布到仓库里，文件名就是笔记的名称，比较好识别，方便后续管理。
这两天尝试使用插件版，发现 `文件规则` 无法设置，并且不单单是 `Hugo` 平台，切换了好几个平台都是这样。

所以请问这块是还没完成，还是啥情况。

**Comment by terwer** [comment]
我以为没有那种需求，新版设置成了别名，并且不可修改。下版本考虑支持修改。
但是GitHub不支持文件名空格，所以真实文件名可能会出问题。gitlab是支持空格字符的。

**Comment by VxRain** [comment]
> 我以为没有那种需求，新版设置成了别名，并且不可修改。下版本考虑支持修改。
> 但是GitHub不支持文件名空格，所以真实文件名可能会出问题。gitlab是支持空格字符的。

我记得之前挂件版的逻辑就是如果有空格的话，校验过不去，不让提交，保持这个逻辑就可以。

如果下个版本支持修改的话，就可以抛弃挂件了😂😂😂

**Comment by terwer** [comment]
下版本加上。

**Comment by terwer** [comment]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/2c68b099-a039-4891-b77c-a2a22d9577ac)
已支持，需升级 `1.18.0`
