### ISSUE TITLE
作者大大，是否考虑文件树结构？

### ISSUE THREAD

**Issue by EaMarWi** [terwer/siyuan-plugin-publisher#820]
如图，类似Obsidain发布那样，使得发布的文章符合思源中的文件树结构
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72482686/d34b57e6-c442-44c6-8b0b-f05523d03e4e)

**Comment by terwer** [comment]
`1.18.0` 支持了可设置发布路径为 [auto] 占位符的情况下目前文档测那估计与实际发布的文件路径保持一致。但是文件树的显示是需要平台自己支持的。

例如：
思源笔记为 `001.专门测试的/001.测试分类1/001.测试正式文章1`，
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/e132e940-dc61-47c6-88b9-7eee83f4ac41)

配置为 `docs/[auto]`
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/0042a7e1-d12b-46d1-9be3-1c20c24071fd)

则发布之后的路径为 `docs/001.专门测试的/001.测试分类1/001.测试正式文章1.md`

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/e5efdf5c-217d-4c96-a44e-c0f8503b0099)

**Comment by Achuan-2** [comment]
@terwer 这个改动现在有一个问题，没设置auto，也会自动加分类到文章里
