### ISSUE TITLE
wordpress html发布时公式无法显示

### ISSUE THREAD

**Issue by lisontowind** [terwer/siyuan-plugin-publisher#822]
wordpress html发布的时候公式无法显示
如图：
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/47842345/78b0cb9c-a509-46a6-bf1d-8f9315e5ee28)
还是希望作者大大改善一下！
我的解决方案：
1. 安装 simple mathjax插件
2. 安装Custom JavaScript插件并替换掉html代码
```
// 选择所有类为 "language-math" 的 div 元素
var mathDivs = document.querySelectorAll('div.language-math');

// 遍历每个 div 元素
mathDivs.forEach(function(mathDiv) {
    // 获取当前文本内容
    var currentText = mathDiv.innerText;

    // 在文本前后添加 $$
    var newText = '$$' + currentText + '$$';

    // 将新文本设置回 div 元素
    mathDiv.innerText = newText;
});

// 选择所有类为 "language-math" 的 span 元素
var mathSpans = document.querySelectorAll('span.language-math');

// 遍历每个 span 元素
mathSpans.forEach(function(mathSpan) {
    // 获取当前文本内容
    var currentText = mathSpan.innerText;

    // 在文本前后添加 $$
    var newText = '$' + currentText + '$';

    // 将新文本设置回 span 元素
    mathSpan.innerText = newText;
});
```
然后渲染好了：
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/47842345/56aa761a-c3a0-4e5f-80e0-65f6164a84e2)

**Comment by terwer** [comment]
步骤2已经内置支持，请升级 `1.18.0`

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/7607c714-dcc8-40ae-8aee-bc9586d5d43f)
