### ISSUE TITLE
建议：保存各个平台的标签和分类

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#838]
以hexo为例，可以保存历史博客的标签和分类，当新的博客发表需要填写时，可以展示历史的标签和分类，一是方便，二是避免创建各种各样的标签和分类别名，比如之前已经创建了机器学习基础标签，后来又新建了机器学习入门等标签

**Comment by terwer** [comment]
当前文档的元数据信息其实是有保存的，在自定义属性里。
某个平台所有文章的历史的标签和分类汇总目前倒是没保存。直接读取汇总可能性能较差。可以持久化到json里面，用[平台key]查询可能较好。具体实现我在想一想，看看怎么避免以后的扩展问题，最后找一个好点的方案。

暂定方案
1. 使用 json 存储，文件名为 platform-metadata.json
2. key 未平台 key，value 为汇总的元数据信息

例如

```json
{
    "platform-metadata": "{\"metadata\":{\"gitlab_Gitlabvuepress\":{\"tags\":[\"siyuan-plugin-publisher\",\"文本处理\",\"标签生成\",\"中文标签\"],\"categories\":[\"临时博客\",\"siyuan-plugin-publisher\",\"开发工具\",\"编程开发\"],\"templates\":[]}}}"
}
```

整理一下，就是下面的数据

```json
{
    "metadata": {
        "gitlab_Gitlabvuepress": {
            "tags": [
                "siyuan-plugin-publisher",
                "文本处理",
                "标签生成",
                "中文标签"
            ],
            "categories": [
                "临时博客",
                "siyuan-plugin-publisher",
                "开发工具",
                "编程开发"
            ],
            "templates": []
        }
    }
}
```

**Comment by Achuan-2** [comment]
发现一个问题，使用hexo上传的时候，会自动加上该笔记的路径为分类，我实际上就打了”技术博客“标签
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/60436214/9c0b3c18-b780-4274-8d09-b34ffcf23fda)
