### ISSUE TITLE
版本比较

### ISSUE THREAD

**Issue by terwer** [terwer/siyuan-plugin-publisher#846]
## 挂件版旧版本 `0.x` <sup>不推荐</sup>

挂件版旧版本最后一个版本是 `v0.8.1`

https://github.com/terwer/sy-post-publisher/tree/v081
https://github.com/terwer/sy-post-publisher/releases/tag/v0.8.1

挂件版免费版新版本 `0.x`

https://github.com/terwer/sy-post-publisher

## 免费版 `1.x+`

目前的所有功能+关键BUG修复+调研之后选择性进行新平台集成。

免费版将停留在 `1.x` 版本。

开源免费版本仓库：https://github.com/terwer/siyuan-plugin-publisher

## 专业版 `2.x+`

免费版所有功能+集成AI+新交互+无限制的平台新增、基于低代码的自定义扩展能力+VIP尊贵表示+公共分享托管+新特性优先新增+BUG优先修复+新平台优先集成。

> 注意 1：集成AI默认提供一个公共共享版本，但是不能确保 key 的长期稳定可用，如需稳定的 AI 体验，需要自行购买 key 。
> 注意 2：出于某些不可描述的原因，公共分享托管服务不在国内，访问速度可能有些延迟，请知悉。

专业版将从 `2.0.0+` 版本开始。

专业版设计理念：

- [X] 分离子项目，代码重构，完善文档。
- [X] 提供零打包、零基础的平台适配器开发能力。
- [X] 最大程度上兼容docker、chrome浏览器、chrome插件等其他环境。
- [X] 100%兼容历史数据、现有平台以及配置。

pro版本仓库：https://github.com/terwer/siyuan-plugin-publisher-pro

**Comment by aantior** [comment]
专业版准备如何收费呢

**Comment by terwer** [comment]
暂时没决定，但是目前初步计划是一次性买断制。专业版目前还未发布，发布之后也会有一段时间试用期。感谢关注。
