### ISSUE TITLE
知乎网页授权失效了

### ISSUE THREAD

**Issue by BopSun** [terwer/siyuan-plugin-publisher#853]
错误提示：10001：请求参数异常，请升级客户端后重试
我无法启用这个功能
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/29018648/91019901-064c-4d9e-a8cc-1b0cf567ee21)

**Comment by terwer** [comment]
试试扫码登录。网页如果限制了，可能改不了。

**Comment by BopSun** [comment]
扫码登陆成功，谢谢！

**Comment by terwer** [comment]
那先使用用扫码登录吧。
