### ISSUE TITLE
hexo 博客会自动添加路径为分类

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#855]
使用hexo上传的时候，会自动加上该笔记的路径为分类，我实际上就打了”技术博客“标签
因为我所有普通笔记都是按日期存放的，这个自动添加路径为分类的功能，我用不到，能否添加一个配置项，取消这个改动呢
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/60436214/9c0b3c18-b780-4274-8d09-b34ffcf23fda)

**Comment by Achuan-2** [comment]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/60436214/2e6acd7d-7d56-4239-a1f9-2affbebba454)

把index.js的目录转化为分类的代码放进if语句里就正常了，原先在if语句外面

**Comment by terwer** [comment]
已修复 1.18.1

保存路径包含 [auto] 的情况下才自动转换，默认不转化。
