### ISSUE TITLE
想问一下，vuepress2支持上传图片吗？

### ISSUE THREAD

**Issue by EaMarWi** [terwer/siyuan-plugin-publisher#856]
不太想另外再配置一个图床，想在上传文章到github时，能够自动上传图片到vuepress的images文件夹下（最好能支持定义图片文件夹路径），引用图片时采用相对链接，这样方面管理，以后也方便迁移。不知道博主能否支持。

**Comment by terwer** [comment]
可能需要增加配置项，因为不是所有人都希望是images文件夹。我先考虑下怎么样实现比较好。

**Comment by terwer** [comment]
supported in `1.20.2`
