### ISSUE TITLE
hexo 平台 Yaml 添加新字段失败

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#866]
比如我想要添加一张题头图，
添加了cover字段，并且点击了保存
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/60436214/cbf328cf-d25d-4c3e-b9c6-bed769f601e6)
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/60436214/1b5ec470-a098-43a3-9337-50e59514b453)
然而更新文章后，Yaml依然是默认的样子，并没有添加成功
就算手动改思源的自定义属性，也是会被默认的Yaml属性覆盖

**Comment by terwer** [comment]
已修复，可升级 `1.18.4`。

**Comment by Achuan-2** [comment]
感谢大佬
