### ISSUE TITLE
csdn 授权停留登录页面很短时间后，直接进入，无登录，然后验证就失败

### ISSUE THREAD

**Issue by BonjourL** [terwer/siyuan-plugin-publisher#887]
csdn 授权停留登录页面很短时间后，直接进入，无登录，然后验证就失败

**Comment by terwer** [comment]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/70c107ad-21d1-499a-b4b1-70fc18e8dda0)
问题未复现，请确保正常浏览器该账号可登录使用。

**Comment by terwer** [comment]
也可使用网页视图插件尝试进入 csdn，然后退出重新登录。
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/160f66ec-7f6a-4bff-808a-4dc3ce58b794)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/6af1db3c-06b1-44ab-b8d4-cbfb4959fa94)

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/17733ad6-43d8-4f4c-8630-319266a14005)

然后重新登录。使用 网页视图插件登录之后，发布工具的验证也是可以用的。

**Comment by BonjourL** [comment]
已解决
