### ISSUE TITLE
支持一键打开已发布平台的对应页面

### ISSUE THREAD

**Issue by BonjourL** [terwer/siyuan-plugin-publisher#892]
能不能支持一键打开已发布平台的对应页面，因为可能想逐个去查看或者在外面对应平台就可以直接点击进入已发布平台的对应页面，而不是得进去之后才能点
![](https://img.leetme.cn/picgo/202311101611383.png)

**Comment by terwer** [comment]
可以支持，先记录。可以加个预览按钮。之前没加其实主要是懒，哈哈😄

**Comment by terwer** [comment]
已支持，请升级 `1.18.8`
