### ISSUE TITLE
hexo 标签和分类无法保存

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#893]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/60436214/610479ac-3b44-4bc4-8a0b-40ea1b869674)

无论是手动填写，还是选历史标签和分类都无法保存到yaml

**Comment by terwer** [comment]
已复现，稍后修复。

**Comment by terwer** [comment]
已修复，晚点可更新 `1.18.8`
