### ISSUE TITLE
重构 YAML 部分逻辑

### ISSUE THREAD

**Issue by terwer** [terwer/siyuan-plugin-publisher#899]
由于 YAML 部分处理最近出现多个问题，#893 #866 现在已经重构。

@Achuan-2 大佬，麻烦有时间更一下 `1.18.9` 试试看，问题应该解决了。之前可能存在不同程度的逻辑覆盖不完整问题。

**Comment by Achuan-2** [comment]
更新了，暂时没发现什么问题
