### ISSUE TITLE
halo平台能不能也支持修改别名的功能

### ISSUE THREAD

**Issue by emanjusaka** [terwer/siyuan-plugin-publisher#905]
halo平台能不能也支持修改别名的功能，halo的预览链接是根据别名生成的，我想要修改这个

**Comment by terwer** [comment]
暂时不支持修改是因为可能部分平台这个是唯一标识，修改了可能导致更新不可用。后续我考虑下看看。

**Comment by terwer** [comment]
已支持，请更新到 `v1.30.2`

https://github.com/terwer/siyuan-plugin-publisher/issues/1530#issuecomment-2544393581
