### ISSUE TITLE
思源2.10.16点击常规发布报错

### ISSUE THREAD

**Issue by Achuan-2** [terwer/siyuan-plugin-publisher#919]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/60436214/23108401-b9b4-4959-b297-0a60ab3c1afd)

**Comment by terwer** [comment]
需要当前文档打开并处于激活状态，我这没有复现。看看是不是其他情况，之前有用户反馈，siyuan.db 别的地方连接的时候会出现无法获取 ID 的情况。

**Comment by Achuan-2** [comment]
重装插件就好了

**Comment by Achuan-2** [comment]
1.
