### ISSUE TITLE
思源发版CSDN失败

### ISSUE THREAD

**Issue by nangongchengfeng** [terwer/siyuan-plugin-publisher#927]
环境版本
```bash
系统：win10
思源：win 当前版本 v2.11.0
发布插件：v1.18.10 
```

```bash
操作失败=>ParseError: KaTeX parse error: Expected 'EOF', got '#' at position 386: …m/kubeadm-init/#̲config-file">ht…
```
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/46562911/a7c43b20-80da-4297-943d-68137e3c907b)

麻烦您看看是否是我操作有问题

**Comment by terwer** [comment]
看起来是公式解析错误，能否提供一下出错的这篇文章，我排查下。方便的话，可以私发出错的这篇文档到 youweics@163.com

**Comment by nangongchengfeng** [comment]
您好，文件已经发送，感谢您的回复和支持





***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "terwer/siyuan-plugin-publisher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月3日(星期天) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [terwer/siyuan-plugin-publisher] 思源发版CSDN失败 (Issue #927)





 
看起来是公式解析错误，能否提供一下出错的这篇文章，我排查下。方便的话，可以私发出错的这篇文档到 ***@***.***

**Comment by nangongchengfeng** [comment]
> 看起来是公式解析错误，能否提供一下出错的这篇文章，我排查下。方便的话，可以私发出错的这篇文档到 [youweics@163.com](mailto:youweics@163.com)

您好，文件已经发送，感谢您的回复和支持

**Comment by terwer** [comment]
问题分析：发布工具使用了Cheerio对 CSDN 的 HTML 进行解析， 然后使用 katex渲染公式。但是Cheerio在处理pre节点时可能出现字符截断的问题。这是由于Cheerio默认将HTML进行简化处理的原因。为了避免这个问题，需要改成使用Cheerio的 xmlMode 选项，这样它会更保守地处理HTML。

已修复，请升级 `1.18.11` 。
