### ISSUE TITLE
BUG：正常打开文档还是提示文档ID不能为空

### ISSUE THREAD

**Issue by EaMarWi** [terwer/siyuan-plugin-publisher#950]
如图，已经正常打开了文档，但是还是提示文档ID不能为空
重启思源不能解决，只能重建牵引才行
这个BUG目前是偶发性的
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72482686/36f97d9b-f71a-4020-bb78-0b062c9d5816)

**Comment by terwer** [comment]
偶发性的不好调试。最好有更进一步的复现背景。
另外，除了顶栏菜单之外，文档的插件菜单也有极速发布，那个不会出现文档ID检测不到的问题。

**Comment by EaMarWi** [comment]
排查出来了，是与增强思源笔记插件冲突了，增强思源笔记插件0.4.0版本和最新的0.5.0都会冲突，只要开启该插件，对已发布文档进行顶栏菜单的一键发布、常规发布、批量发布都会提示“文档ID不能为空”。
这是发布插件的偏好设置：
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/72482686/227c8903-41ae-4439-a9f6-71a81f19dd3b)

**Comment by terwer** [comment]
这样啊，我晚上看看，可能的话我去给插件作者 pr 一下，感谢反馈🫶

**Comment by terwer** [comment]
看看最新版增强笔记插件是否解决。
