### ISSUE TITLE
Docker版思源笔记 插件没有支持

### ISSUE THREAD

**Issue by Wuqiyang312** [terwer/siyuan-plugin-publisher#958]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/86960631/0377b784-6a65-444f-be74-9a4c7e8fce47)
Docker 镜像地址：[https://hub.docker.com/r/b3log/siyuan](https://hub.docker.com/r/b3log/siyuan)

**Comment by terwer** [comment]
docker 版本在体验支持中，因为还不完善，暂时没放出来。后续等 docker 版本功能文档会放开。敬请期待！

**Comment by terwer** [comment]
#1009 跟踪
