### ISSUE TITLE
Mac上发布到知乎依旧存在公式解析错误

### ISSUE THREAD

**Issue by Lingyu-Meng** [terwer/siyuan-plugin-publisher#964]
OS: macOS Sonoma 14.2, 14.2.1
Siyuan: 2.11.1 
siyuan-plugin-publisher: 1.18.11
问题包括：
1. 公式无法解析
2. 块间距没有取消，发布后段落依旧额外空行
3. 验证成功但无法获取专栏信息(显示为‘暂无数据’)

**Comment by terwer** [comment]
验证成功但无法获取专栏信息 这个要看一下是不是用户名写错了，注意是 url 上面的英文，不是昵称 。其他两个我验证下，但是格式控制不一定能完全满足。

例如 
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/dded5eec-e06f-4d9c-b61a-d43e23167ca4)

**Comment by terwer** [comment]
问题跟进
1、公式无法解析，麻烦提供一下不能解析的公式文本
2、块间距这个不会做处理，我们不会额外处理费 md 语法之外的格式。这样做也是为了保证最大的兼容性。

**Comment by Lingyu-Meng** [comment]
实际上似乎任何公式都无法解析，这里贴一下刚刚试了的两个
$$U_{i}(x)=x_{i}-\alpha_{i} \frac{1}{n-1} \sum^{j\neq i}_{i,j\in \{ 1,...,n\} } max\{ x_{j}-x_{i},0\} -\beta_{i} \frac{1}{n-1} \sum^{j\neq i}_{i,j\in \{ 1,...,n\} } max\{ x_{i}-x_{j},0\}$$

$V^{k}_{i}(t)=\begin{cases}\frac{\phi \cdot N\left( t-1\right) \cdot V^{k}_{i}(t-1)+\pi_{i} \left( s^{k}_{i},s_{-i}(t)\right) }{N(t)} ,&s^{k}_{i}=s_{i}(t)\\ \frac{\phi \cdot N(t-1)\cdot V^{k}_{i}(t-1)+\delta \cdot \pi_{i} \left( s^{k}_{i},s_{-i}(t)\right) }{N(t)} &s^{k}_{i}\neq s_{i}(t)\end{cases}$

它们在思源内显示正常，发布后成为latex了。
<img width="811" alt="截屏2024-01-08 06 06 32" src="https://github.com/terwer/siyuan-plugin-publisher/assets/147720003/9edbad60-1fef-456b-a033-690ec22ce086">
<img width="707" alt="截屏2024-01-08 06 06 57" src="https://github.com/terwer/siyuan-plugin-publisher/assets/147720003/71938c6e-5acc-4b25-9c71-c850360224c7">

**Comment by terwer** [comment]
经验证，知乎公式显示确实存在这个问题。`1.18.12` 将会修复，预计1/9 之前发布，感谢您的反馈。

关于专栏获取问题，可以参考下方指引
![](https://img1.terwer.space/api/public/202401081630796.png)

**Comment by Lingyu-Meng** [comment]
更新至v1.19.0后问依旧存在，且无法识别markdown语法与上传图片。
<img width="709" alt="截屏2024-01-10 16 15 29" src="https://github.com/terwer/siyuan-plugin-publisher/assets/147720003/8de68410-64fa-4c51-9013-54339d0e9657">
<img width="779" alt="截屏2024-01-10 16 15 54" src="https://github.com/terwer/siyuan-plugin-publisher/assets/147720003/a7ae0324-dd59-40bd-8ce1-89815c5758aa">

**Comment by terwer** [comment]
目前 `知乎` 和 `CSDN` 只能选择 HTML 模式发布。
目前 `知乎` 和 `CSDN` 只能选择 HTML 模式发布。
目前 `知乎` 和 `CSDN` 只能选择 HTML 模式发布。

请在设置中将发布模式修改为 HTML 即可正常使用。
