### ISSUE TITLE
已经发出的文章，无法使用AI的摘要功能

### ISSUE THREAD

**Issue by FuTianXing** [terwer/siyuan-plugin-publisher#970]
对于已经发出的文章（wordpress平台），无法在常规模式下用AI提取摘要，提示：**请求错误，请在偏好设置配置请求地址和ChatGPT key！**

另外，AI的聊天模式中没有页面的自动换行，一整大段都显示为一行，要横向拖动下面的滚动条才可以看到全部内容，很不方便。

**Comment by terwer** [comment]
问题1，请求错误一般是ai服务不稳定导致。详细信息可以打开开发者工具跟踪。发布工具本身并不提供ai服务，用的是思源笔记用户配置的key。

对问题2，ai聊天界面目前还比较简陋，确实还有优化的空间。后续会调整。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月05日 22:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-publisher] 已经发出的文章，无法使用AI的摘要功能 (Issue #970) |

对于已经发出的文章（wordpress平台），无法在常规模式下用AI提取摘要，提示：请求错误，请在偏好设置配置请求地址和ChatGPT key！

另外，AI的聊天模式中没有页面的自动换行，一整大段都显示为一行，要横向拖动下面的滚动条才可以看到全部内容，很不方便。

**Comment by terwer** [comment]
上面已回复解释，目前不存在发布平台需要优化的地方，先关闭了。有疑问欢迎跟帖提供更加详细的场景。
