### ISSUE TITLE
CSDN发布失败，无标签

### ISSUE THREAD

**Issue by chenanga** [terwer/siyuan-plugin-publisher#971]
⚠️错误提示
操作失败=>Error: 请设置文章标签

平台配置指南的网页504
https://blog.terwer.space/s/20230810132040-nn4q7vs

**Comment by terwer** [comment]
这个是正常的。CSDN必须要求设置标签。是平台的限制。不是bug。在文档上加上标签即可。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月06日 21:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-publisher] CSDN发布失败，无标签 (Issue #971) |

⚠️错误提示
操作失败=>Error: 请设置文章标签

平台配置指南的网页504
https://blog.terwer.space/s/20230810132040-nn4q7vs

**Comment by chenanga** [comment]
您好，但是我设置了有标签，也不行。
![Uploading image.png…]()

而且那个ai提取标签的也不行，本地思源ai是可以使用的(那些apikey都是配置好的)

**Comment by chenanga** [comment]
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/38496970/26fbd784-4293-4d71-9f82-af1b4619e21c)

**Comment by terwer** [comment]
先用常规发布试试。我回头排查下极速发布，看看能否复现问题。

**Comment by terwer** [comment]
经验证，未复现问题。添加标签可以即时生效。如有详细步骤可在比回帖。

![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/84f3d2c5-9a7d-4688-97f3-d0d64333f254)
