### ISSUE TITLE
历史配置遗留导致按照文档配置之后，还是不能发布，插件报错 TypeError: Cannot set properties of undefined (setting 'knowledgeSpaceReadonlyModeTip')

### ISSUE THREAD

**Issue by ethan1010** [terwer/siyuan-plugin-publisher#972]
中间隔了好几个月

尝试好几次，每次都尝试了好几个发布途径。主要想搞定简书，一直不行。。尝试notion、博客园也不行。。

让我产生的非常深的怀疑。

看配置不复杂，但为啥就是不行。。

**Comment by terwer** [comment]
请删除旧配置，安装最新版本。提供具体的操作步骤，错误信息。目前所有已支持平台都是可以正常工作的。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月07日 16:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [terwer/siyuan-plugin-publisher] 这个插件能正常work吗？ (Issue #972) |

中间隔了好几个月

尝试好几次，每次都尝试了好几个发布途径。主要想搞定简书，一直不行。。尝试notion、博客园也不行。。

让我产生的非常深的怀疑。

看配置不复杂，但为啥就是不行。。

**Comment by terwer** [comment]
请提供详细环境、报错信息、操作步骤等有用信息，感谢你的呢反馈。

**Comment by ethan1010** [comment]
win下，思源最新版本
删除插件，关闭思源，重新安装插件，选择简书登录成功，点击验证报错：作失败=>TypeError: Cannot set properties of undefined (setting 'knowledgeSpaceReadonlyModeTip')

**Comment by terwer** [comment]
按照说明删除配置文件重新初始化。我怀疑是很早的错误配置残留导致。可以去『工作空间』/data/storage/syp/syp.plus.cfg.json删除他重启。删除他重启删除他重启。注意此操作后所有配置会重新初始化。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月10日 19:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [terwer/siyuan-plugin-publisher] 这个插件能正常work吗？ (Issue #972) |

win下，思源最新版本
删除插件，关闭思源，重新安装插件，登录成功，点击验证报错：作失败=>TypeError: Cannot set properties of undefined (setting 'knowledgeSpaceReadonlyModeTip')

**Comment by ethan1010** [comment]
终于可以了，多谢

建议优化一下：
1. 在产品页面中添加对应的说明，我在几个月内尝试，看使用文档都没有找到对应的解决方法。
2. 安装新版本的时候，老的配置文件转为新的配置文件。  这样就不会有问题了。

**Comment by terwer** [comment]
非常感谢你的诚恳建议，解答如下：
1、其实这个已经在文档写了，可能不够明显没有注意到，可以看看文档 FAQ 2 和 3。
![image](https://github.com/terwer/siyuan-plugin-publisher/assets/3259282/adfe995b-f330-4234-8d66-7560db1ac98f)

文档地址：https://blog.terwer.space/s/20230810132040-nn4q7vs

另外，还有一些其他用户遇到过的情况，我也基本列了一些。

2、老的配置文件转为新的配置文件这个没有做是为了最大程度是保留用户配置。不过您的这个建议非常好。我会在反复验证的情况下，尝试增加自动迁移功能。我先打开 issue，后续研讨一下最合适的配置更新方案。

TODO：配置文件自动迁移功能完成之后再关闭此 issue。
